import streamlit as st
import requests
import os
from streamlit_chat import message

# Konfigurasi API
API_KEY = "DVLwE5b14BGdOsPI52PztoLcl2AZRuSY3bW25YQ4XXs86rKYUAI8JQQJ99ALACYeBjFXJ3w3AAABACOG2DsP"  # Ganti dengan API Key Anda
ENDPOINT = "https://chatbot-abstrak.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-02-15-preview"

headers = {
    "Content-Type": "application/json",
    "api-key": API_KEY,
}

# System prompt lengkap Anda
system_prompt = """
Role:
Anda adalah chatbot yang dirancang untuk memperbaiki dan meningkatkan kualitas abstrak yang diinputkan oleh pengguna. Tugas utama Anda adalah menganalisis abstrak yang diberikan oleh pengguna dan memperbaikinya berdasarkan pola, struktur, dan gaya penulisan yang terdapat dalam kumpulan data abstrak yang telah disediakan. Anda tidak diperkenankan untuk menjawab pertanyaan diluar konteks perbaikan abstrak.

Konteks dan referensi:
Anda akan mempelajari kumpulan data abstrak berikut sebagai referensi untuk memahami struktur, terminologi teknis, dan gaya penulisan yang diharapkan. Berikut adalah contoh-contoh abstrak yang harus Anda pelajari:

- Suatu alat cetak foto (afdruk), yang terdiri dari suatu susunan kerangka-kerangka pendukung terbuat dari bahan plastik pralon yang anti karat yang meliputi: dop pralon 4" x 5" (2), dop pralon $ 5" (3), pelat plastik teplon (4), over lup pralon $ 2" x 3" (5), sambungan talang U yang sudah dipotong (6), sambungan T 4> 3/4" (7), sambungan KNI 0> 3/4" (8) dan sok daun 4" (1) menyorot ke suatu lensa cembung-cembung didalam pralon $ 4" (12) terpasang secara tetap (permanen) sebagai pengumpul sinar ke film negatif (13) yang terdapat pada pelat teplon (4) yang akan ditembus sinar yang telah terkumpul tersebut diteruskan ke dalam pralon $ 2" (14) bagian atas, dimana pada pralon 2" (14) bagian atas terpasang rakitan lensa (14b) yang dapat bergerak mengikuti alur spiral tersebut dengan bergerak ke atas/ke bawah terhadap pada pralon $ 2" {14) bagian bawah terpasang rakitan lensa over lup <5 2" x 1" (14a), maka saat pralon O 2" (14) diputar secara manual, maka jarak antara kedua lensa tersebut (14a dan 14b) dapat digerakkan menjauh/mendekat secara manual untuk menghasilkan titik fokus pada kertas foto (15).

- Penemuan ini berhubungan dengan aparatus penggerak perangkat pensakelaran dari pemutus, rangkaian yang mampu melakukan kerja yang lebih mudah bila menghubungkan atau memutus perangkat pensakelaran dari terminal pemutus rangkaian selama perawatan dari pemutus rangkaian. Selain itu, dimungkinkan untuk melakukan perawatan tanpa membuka pintu depan dari rumahan pemutus rangkaian. Aparatus penggerak perangkat pensakelaran dari pemutus rangkaian menurut penemuan ini terdiri dari kereta untuk menopang perangkat pensakelaran dari pemutus rangkaian, perangkat penggerak kereta untuk menggerakkan ke depan clan ke belakang kereta, clan rakitan balok penopang yang secara dapat dilepaskan dipasang pada rumahan untuk penetapan atau pemisahan perangkat penggerak kereta pada posisi tertentu.

- Penemuan ini berhubungan dengan suatu alat pengumpan bahan lembaran yang terdiri dari suatu puli penggerak (I); suatu bagian penggoyang yang terdiri dari: suatu rol penggoyang pertama (6) yang dihubungkan ke puli penggerak (1) melalui suatu sabuk vakum (12), suatu rol penggoyang kedua (7), suatu sarana penggoyang (5), suatu bagian eksentrik (3) yang terletak secara tetap pacta suatu puli gerak (2) yang digerakkan oleh puli penggerak (1) melalui suatu sabuk, dan suatu penghubung (4), rol penggoyang pertama (6), rol penggoyang kedua (7) dan sarana penggoyang (5) tersebut digerakkan maju-mundur oleh bagian eksentrik (3) melalui penghubung (4); suatu rol perantara pertama (9) yang dihubungkan dengan rol penggoyang pertama (6) melalui sabuk vakum (12); suatu bagian vakum (13) yang mempunyai lubang-lubang hisap dan katup vakum yang ditempatkan tepat dibawah lubang-lubang hisap; suatu rol perantara kedua (10) yang dihubungkan dengan rol perantara pertama (9) melalui sabuk vakum (12) dimana sabuk vakum (12) tersebut berada dibawah bagian vakum (13); rol perantara kedua (10) tersebut dihubungkan ke rol penggoyang kedua (7) oleh sabuk vakum (12); suatu rol perantara ketiga (11) yang dihubungkan ke rol penggoyang kedua (7) dan ke puli penggerak (1) oleh sabuk vakum (12); dan suatu meja pengumpan (24) yang ditempatkan dibawah bagian vakum (13).

- Pengendalian hama dan penyakit tanaman sampai saat ini masih tergantung pada penggunaan pestisida sintetik yang menghadapi kendala berkaitan dengan harga pestisida yang tinggi. Di samping itu sifat pestisida yang mudah larut dalam air menyebabkan pestisida mudah tercuci oleh air hujan, sehingga keefektifannya berkurang dan pestisida yang larut dapat mengganggu lingkungan perairan. Untuk mengatasi masalah tersebut, penelitian di Unit Penelitian Bioteknologi Perkebunan telah menghasilkan formula sticker (bahan perekat) alamiah (non sintetik) tanpa efek sampingan, yang sesuai untuk berbagai jenis pestisida. Penggunaan sticker menyebabkan bahan aktif pestisida tidak mudah tercuci air hujan, sehingga tidak diperlukan penyemprotan berulang-ulang. Produksi dan pengembangan produk sticker dengan bahan lateks yang mengandung sabun, ammonia, dan antioksidan menjadi hak dan wewenang penemu dan Unit Penelitian Bioteknologi Perkebunan.
Suatu standar tegak yang bekerja dengan sistem listrik untuk sepeda motor yang memiliki suatu alat penggerak, suatu tabung yang terhubung dengan kuat ke bagian luar dari alat penggerak tersebut, suatu poros yang dikendalikan oleh alat penggerak tersebut yang dapat dimasukkan dan dapat meluncur ke dalam tabung, suatu alat penghubung yang terhubung diantara poros dan dua kaki tersebut yang dihubungkan dengan dapat bertumpu pada sepeda motor tersebut. Dengan susunan yang demikian, standar tegak sepeda motor tersebut dapat dioperasikan secara listrik untuk menyajikan atau melepaskan topangan terhadap sepeda motor tersebut.

- Penemuan ini berkaitan dengan perangkat sakelar jungkat-jungkit yang dipasang pada permukaan-permukaan dinding dalam rumah untuk pengatur ON/OFF dari penerangan dan perlengkapan listrik yang sejenisnya pada permukaan- permukaan dinding yang mencakup atap, masing-masing perangkat tersebut mencakup pelat dinding yang terbenam rata yang mempunyai dua atau tiga tuas sakelar berbentuk pelat yang dapat digerakkan secara berayun untuk pengoperasian dua atau tiga sakelar ON/OFF yang ditancapkan pada pelat dinding.
Pipa saringan "pre-pack" dan "super pre-pack" pada sumur minyak yang mempunyai masalah kepasiran atau kotoran lainnya mempunyai disain khusus ,terutama disain pada ring (5) yang terletak didalamnya yaitu bentuknya dibuat miring atau tirus, dimana ring tersebut ditempatkan di kedua ujung-ujung bagian atas dan bagian bawah di dalam dalam suatu pipa saringan pada saluran pipa perforasi minyak sehingga ketika peralatan atau perkakas dalam (6) dimasukkan kedalam saluran pipa perforasi untuk suatu keperluan perbaikan atau produksi, maka tidak akan terjadi penyangkutan di ujung pipa saringan, demikian pula ketika peralatan atau perkakas dalam (6) akan ditarik keluar maka saringan tidak akan menyangkut yang mengakibatkan akan ikut terangkat keluar. Ring pemandu (5) yang miring berbentuk tirus tersebut akan mengunci komponen-komponen saringan yang terdiri dari pasir/resin coated sand (4), Saringan (3), dan pipa perforasi bagian dalam pipe (2) pada diameter paling dalamnya yang terpasang didalam pipa perforasfbagian luar (1).

- Penemuan ini menyajikan bentuk-bentuk kristalin dari adefovir dipivoksil metode-metode untuk menyediakan kristal-kristal tersebut. Komposisi-komposisi dan metode-metode penemuan ini memiliki sifat-sifat yang dikehendaki untuk sintesa berskala besar dari adefovir dipivoksil kristalin atau untuk formulanya kedalam dosis-dosis terapi. Komposisi-komposisi penemuan mencakup bentuk kristal anhidrat dari adefovir dipisoksil. 
Metode dan peralatan disediakan untuk menilai kualitas padi yang akan dipanen dari tanaman padi di kemudian hari, selama masa pertumbuhan sebelum panen. Metode tersebut terdiri dari langkah untuk menetapkan koefisien perubahan kualitas untuk menilai kualitas padi tertentu setelah panen berdasarkan daya serap yang berhubungan dengan kualitas padi tertentu yang diperoleh dengan menyinarkan cahaya yang memiliki daerah panjang gelombang yang telah ditentukan pada daun tanaman padi yang tumbuh pada waktu yang telah ditentukan selama masa pertumbuhan tanaman padi dan kualitas tertentu yang diperoleh dari padi yang sama setelah panen, dan langkah untuk menilai kualitas padi yang akan dipanen di kemudian hari berdasarkan koefisien perubahan kualitas dan daya serap tersebut yang berhubungan dengan kualitas tertentu tersebut yang diperoleh dari daun tanaman padi yang sedang tumbuh pada waktu yang telah ditentukan. Pengukuran untuk menilai kualitas padi dapat dilakukan dengan cara yang mudah dan sederhana selama pertumbuhan tanaman padi.

- Zat-zat warna azo yang terdiri dari setidaknya satu unit struktur dari rumus (1) Zat-zat warna azo menurut penemuan ini terutama sesuai untuk pewarnaan (pencelupan) bahan serat kapas dan wol dan menghasilkan hasil pewarnaan dengan sifat-sifat keseluruhan yang baik. 
Suatu rangka kusen untuk pintu belakang kargo boks dari kendaraan jenis ringan, setengah ringan, atau berat yang melliputi rangka kusen atas-bawah dalam arah mendatar; dan rangka kusen kiri-kanan dalam arah tegak. Masing-masing rangka tersebut dirangkai menjadi suatu rangka kusen kendaraan kargo boks untuk pintu belakang. Rangkaian rangka kusen tersebut diatas memiliki bagian alur (sekoneng) untuk menempatkan rangka atau daun pintu secara rapat. Rangka atas memiliki bagian pembentuk topi sebagai bagian dari bentuk profil yang digunakan, bagian alur (sekoneng) dan bagian topi yang terbentuk bertujuan untuk merapatkan dan menghindari masuknya air ke dalam ruang kargo boks, dan rangka bawah membentuk bamper yang melekat pada bagian casis atau rangka tambahan pada ujung lantai bawah dari kargo boks. Bagian alur (sckoncng) yang terbentuk bertujuan untuk merapatkan dan menghindari masuknya air ke dalam ruang kargo boks bagian bawah.

- Pentingnya pencegahan pencemaran lingkungan laut yang diakibatkan oleh air got ( campuran minyak dan air) yang berasal dari selokan kamar mesin kapal, dan keterbatasan dari ruangan kapal kecil yang tersedia menimbulkan suatu ide dan inovasi baru untuk menciptakan suatu alat pemisah air dan minyak. ruangan minyak kotor memiliki bentuk yang sederhana dan ukuran yang kecil sehingga memudahkan untuk penempatan di dalam kapal. Ruangan minyak kotor memiliki fungsi ganda,selain untuk memisahkan air dan minyak, juga berfungsi untuk menampung minyak khusus kapal kecil. fungsi ganda ini yang memberikan peranan dalam mengatasi keterbatasan pada ruangan kamar kecil.

- Sebuah alat pengering super untuk mengatur kelembaban relatif (RH) pada pengangkutan kargo dengan kontainer, yang terbuat dari bahan polypropilene, memiliki suatu bahan pengering (dessicant) seperti pengkristalan garam jenuh CaCl2 77%, yang berfungsi untuk menyerap air dari udara, dan dapat dengan mudah diletakkan dengan cara digantung secara tegak lurus pada ruangan kontainer atau ruangan-ruangan dari kapal pengangkut kargo. Alat ini terdiri dari : sebuah unit bagian belakang (1) , yang sekaligus terdapat tempat pengkristalan gram jenuh CaCl2 (2), dan tempat menempatkan lengan karton berlekuk (3) sebagai tempat menampung air, sebuah unit bagian depan (4), yang sekaligus terdapat sebuah lubang empat-persegi (5) dan sebuah filter (6) terbuat dari aluminium yang akan menutup lubang tersebut.

- Telah diberikan metode pembentukan isolasi zonal diantara bagian dalam dan bagian luar suatu bagian sistem sumur bawah-tanah tanpa selubung yang berdampingan dengan bagian sumur yang dilengkapi selubung. Metode tersebut mencakup penyisipan pipa yang dapat diekspansi menembus selubung sumur yang ada masuk ke dalam bagian sumur tanpa selubung - seperti cabang lateral suatu sistem sumur bawah-tanah - dan selanjutnya melaksanakan ekspansi atas pipa yang dapat diekspansi tersebut sedemikian sehingga salah satu ujung pipa tersebut menekan dinding bagian sistem sumur tanpa selubung sedangkan permukaan luar ujung lainnya menekan permukaan dalam selubung sumur, dengan demikian diperoleh interferensi-pasang yang mampu menghasilkan ikatan-geser dan perapatan hidrolik di antara permukaan di sekelilingnya.

- Penemuan ini secara umum berhubungan dengan proses pemisahan dimana arus umpan multi-komponen dimasukkan ke dalam sistim pemisahan yang beroperasi di bawah kondisi pembentukan padatan untuk sekurang-kurangnya satu komponen arus umpan. Komponen yang dapat membeku, meskipun secara khusus CO2, H2S atau gas asam lain, dapat berupa komponen yang memiliki potensi membentuk padatan dalam sistem pemisahan. Arus umpan multi-komponen dimasukkan ke dalam sistem pemisahan, sekurang-kurangnya sebagian beroperasi di bawah kondisi pembentukan padatan untuk sekurang-kurangnya satu komponen arus umpan. Arus uap diambil dari daerah atas pada sistem pemisahan dan dikompresi hingga arus bertekanan lebih tinggi. Sekurang-kurangnya sebagian arus yang dikompresi didinginkan dan kemudian diekspansi hingga dikompresi didinginkan dan kemudian diekspansi hingga tekanannya lebih rendah untuk selanjutnya mendinginkan arus yang dikompresi. Sekurang-kurangnya sebagian dari arus yang diekspansi dikembalikan ke sistem pemisahan, dengan demikian memberikan refrigerasi pada sistem pemisahan.
suatu cetakan untuk membuat pelet/tablet yang terdiri dari: suatu bodi cetakan (10) berbentuk tabung silinder yang memiliki rongga cetakan (35) di bagian tengah sepanjang bodi cetakan; suatu tonjolan penahan (20) yang dibentuk pada sekeliling bagian sebelah atas dan bawah bodi cetakan (10); suatu ram atas (5) yang berfungsi sebagai penekan bahan serbuk yang akan dibuat pelet di dalam rongga cetakan (35), yang mencakup suatu kepala ram dan suatu batang penekan; suatu ram bawah (15) sebagai penyangga bodi cetakan (10) ketika bahan serbuk akan dibuat pelet; suatu batang penekan (30) untuk mengeluarkan ram atas (5) dari bodi cetakan (10); yang dalam hal ini disediakan dengan suatu silinder penyangga (25) yang berfungsi untuk mempermudah pengeluaran pelet/tablet hasil cetakan dari dalam rongga cetakan (35), dimana diameter dalam (d4) dari silinder penyangga (25) tersebut lebih besar dari pada diameter luar (d1) dari ram atas (5) dan bawah (15).

- Penemuan ini berhubungan dengan suatu alat pengkopel yang terdiri dari rumahan jantan (10) yang mempunyai bukaan atas (lla) dan bukaan bawah (lib) yang didalamnya ditempatkan klep pengaman buka-tutup (12), dan pegas spiral (13); dan suatu rumahan betina yang dilengkapi dengan sarana pemutar yang mempunyai bukaan betina atas dan bukaan betina bawah yang didalamnya ditempatkan lintasan penahan (22), katup pendorong (23), bagian ceruk betina (24), dan bagian tonjolan (25).

- Pokok penemuan menyajikan suatu film yang memiliki sekurang-kurangnya satu lapisan yang terdiri atas suatu interpolimer etilena dan sekurang-kurangnya satu komonomer yang dipilih dari golongan yang meliputi a-olefin C3-C20, diena, dan sikloalkena, dimana interpolimer adalah dicirikan memiliki derajat kemudahan pemrosesan yang tinggi, performa optik yang baik, dan sifat-sifat mekanis yang baik. Pokok penemuan selanjutnya menyajikan proses fabrikasi film dan komposisi polimer yang berguna dalam pembuatan film subjek. 

- Sebuah termos es batu yang terbuat dari buah kelapa asli dan telah melalui proses pekerjaan akhir sehingga benar-benar mempunyai ciri yang khas dari buah kelapa yang sudah kering. Termos es batu menurut penemuan ini terdiri dari bagian badan (1) untuk wadah tempat menampung es batu di dalamnya, dan bagian tutup (2) untuk menutup bagian badan tersebut. Pada permukaan bagian dalam dari tutup (2) dapat ditempatkan kayu tambahan, sedangkan pada dasar dari bagian badan (I) dapat dipasang alas atau tatakan.

- Suatu mesin pemipil jagung yang komponen utamanya terdiri dari silinder kayu dengan gigi pemipil (15) yang telah diperkuat dengan besi beton (22) dan sarangan bergetar (14) yang digantung dengan pegas karet (13) serta menggunakan tenaga penggerak motor bakar bensin 7 hp (5), telah dapat meningkatkan kapasitas pemipilan dengan tingkat kerusakan biji jagung lebih kecil dan efisiensi penggunaan energi lebih tinggi seperti terbukti dari persentase tongkol jagung patah yang lebih kecil dari mesin pemipil jagung lokal.

- Dalam mesin hidrolik dengan baling-baling yang dapat bergerak, sejumlah baling-baling pemutar (3) dipasang secara radial, setiap baling-baling pemutar (3) memiliki permukaan ujung atas (3a) termasuk dalam permukaan bola dengan terpusat pada sambungan sumbu L poros utama (5) dan sumbu M batang penyemat baling-baling pemutar. Jari-jari tonjolan pemutar RC yang menonjol pada bidang tegak lurus terhadap sumbu L poros utama (5), dimana baling-baling pemutar (3) diatur dalam posisi tertutup penuh, adalah lebih kecil dari pada jari-jari R permukaan bola teramsuk permukaan ujung atas (3a) baling-baling pemutar (3). 

- Dua ruang sub-pengawaangaram d1 dan d2 ditentukan oleh membran penukaran kation (3) pada salah satu sisi, membran penukaran anion (4) pada sisi yang lain, dan membran penukaran ion antara (5) diantaranya dan diisi dengan bahan penukaran ion (8) untuk menyusun ruang pengawaangaram D. Ruang penghubung 1 diberikan melalui membran penukaran kation (3) dan membran penukaran anion (4) pada kedua sisi ruang pengawaangaram D. Ruang pengawaangaram D dan ruang pengkonsentrasi (1) diberikan di antara anoda (1) dan katoda (8). Sedangkan voltage yang dipakai diantara anoda (7) dan katoda (6), air yang dipasok ke salah satu dari dua ruang sub-pengawaangaram d2 dan kemudian air yang dikeluarkan dari ruang sub-pengawaangaram pertama d2 dipasokkan ke ruang sub-pengawaangaram ke dua d1. Air konsentrat dipasokkan ke ruang konsentrat. Dengan susunan ini, ion yang tidak murni dalam air yang diolah yang mengalir dalam ruang pengawaangaram D dikonsentrasikan dalam air konsentrat dan air yang diawaionkan dihasilkan. 

- Suatu kepala api dari suatu kompor gas yang terdiri dari suatu bagian kepala api utama (7) yang berbentuk lingkaran berongga dengan ketebalan tertentu dengan lubang-lubang kepala api (8) di sekeliling permukaan bagian atas dari kepala api utama (7) tersebut, suatu bagian cerobong kepaJa api (9a, 9b) yang ditempatkan dan disatukan dibagian sebelah bawah kepala api utama (7) yang pada bagian pangkalnya dibentuk dengan suatu rongga mulut cerobong (dl, d2), pada rongga cerobong (mulut cerobong) (dl, d2) terjadi pencampuran tahap pertama (a) antara udara/oksigen dan bahan bakar gas dan campuran tahap pertama (a) dari udara dan bahan bakar gas ini selanjutnya masuk ke dalam bagian kepala api (7) dan pada bagian cekungan kepala api (12) dilakukan pencampuran tahap kedua (b), serta dilanjutkan dengan pencampuran tahap ketiga (c) yang dilaksanakan pada lubang-lubang kepala api (8) yang akhimya akan menghasilkan pembakaran gas dari pencampuran tahap ketiga (c) tersebut menjadi sempuma, stabil, efisien dan tanpa asap hitam.

- Suatu pengemas yang dapat dibuka dan ditutup kembali dengan rapat serta dapat berdiri dengan tegak yang terdiri dari: bodi pengemas yang terbuat dari resin sintetis seperti poliester, polistirin, polipropilin atau bahan kertas, aluminium foil, atau sejenisnya; lapisan permukaan dalam berbentuk suatu kantung yang dapat diisi yang terbuat dari resin sintetis seperti polietilin, polivinil klorida, polipropilin atau sejenisnya dengan ketebalan antara 20 hingga 200 mikron; dimana lapisan permukaan dalam direkatkan dengan panas sehingga keduanya membentuk suatu struktur kantung yang memungkinkannya untuk ditempatkan secara dapat berdiri manakala kantung pengemas sudah dimuati; dan suatu bagian pembuka dan penutup yang terpasang pada bodi pengemas pada bagian permukaan dalam kemasan yang dibuat khusus untuk mencegah isi kemasan keluar atau tertumpah akibat dari pengemas jatuh atau ada tekanan terhadap pengemas yang akan mungkin menyebabkan penutup pengemas terbuka yang nantinya menyebabkan isi pengemas kurang aman dan tidak terlindungi dengan baik.

- Suatu kantung yang mempunyai bagian yang menonjol kearah luar pada salah satu sisi vertikal sebelah atas yang terdiri dari bodi kantung dan alas, dimana bodi kantung dibentuk oleh dua lembaran plastik, masing-masing lembaran plastik mempunyai bagian yang menonjol kearah luar, sisi-sisi vertikal kedua lembaran tersebut direkat secara panas demikian juga sisi atasnya untuk membentuk bodi kantung dan bagian yang menonjol keluar yang berongga didalamnya dengan ujung tertutup. Dasar kantung merupakan suatu lembaran plastik yang ditekuk kearah bawah tepi keliling luarnya dan permukaan luar dari bagian yang ditekuk direkat secara panas dengan permukaan sebelah dalam tepi keliling bawah bodi kantung untuk membentuk kantung.

- Suatu panci (1) untuk memasak air yang dilengkapi dengan suatu pipa yang dibentuk seperti spiral (5) didalam nya. Api dari sumber panas yang berada dibawah panci (1) mengarah ke dasar panci (7) dan ke sejumlah lubang (9) yang terdapat didasar panci (7) sehingga energi panas dari api tersebut dikonveksikan pada dasar panci dan pada pipa (5) sehingga dasar panci (7) dan pipa (5) tersebut menjadi panas selanjutnya energi panas pada dasar panci (7) dan pada pipa (5) dikonduksikan secara merata pada air yang berada didalam panci sehingga air tersebut menjadi cepat mendidih.

- Aplikator dengan tampon kesehatan terdiri dari tabung silinder luar dan pengisap bagian dalam yang secara aksial dapat digerakkan dalam tabung silinder luar untuk menyemprotkan tampon keluar dari bukaan ujung depan dari tabung silinder luar, dan tabung silinder luar diberi ukuran lebih besar dari panjang tampon tersebut, 50 ~ 80 mm. 

- Aplikator (1) untuk tampon kesehatan terdiri dari tabung silinder luar (2) yang dibentuk dengan daerah diamater luar maksimum (11). Tabung silinder luar (2) mempunyai diameter luarnya yang secara bertahap meningkat kebelakang dari ujung depannya sampai daerah diameter luar maksimum (11) dicapai dan kemudian secara bertahap menurun kebelakang. Daerah diameter luar maksimum (11) memanjang dalam 1/2 dari panjang keseluruhan tabung luar (2) yang diukur dari ujung depannya. 

- Penemuan ini menyediakan suatu metode untuk pembuatan polimer yang terdiri dari memperlakukan monomer yang mengandung paling sedikit senyawa tak-jenuh polar dengan polimerisasi anion dengan adanya senya fosfazenium yang diwakili oleh formula (1) : (dimana Z- merupakan anion dari senyawa hidrogen aktif dalam bentuk dimana proton dieliminasi dari senyawa hidrogen aktif dan dipindahkan ke anion tersebut; a, b, c dan d masing-masing mewakili 1 atau 0, tetapi semua secara bersamaan tidak boleh nol; dan R dapat sama atau berbeda dan masing-masing mewakili gugus hidrokarbon yang mempunyai 1 sampai 10 atom karbon, dan dua R (s) pada atom nitrogen yang sama secara opsional terkombinasi satu dengan lainnya untuk membentuk struktur siklik atau dengan adanya senyawa fosfazenium dan senyawa hidrogen aktif. Polimer yang dihasilkan dicirikan dengan distribusi berat molekul yang sempit.

- Invensi ini menyediakan suatu teknik produksi secara selektif suatu polimorf yang diinginkan dari asam 2-(3-siano-4-isobutiloksifenil)-4-metil-5-tiazolkarboksilat. Invensi ini juga menyediakan suatu metode produksi berbagai polimorf dari asam 2-(3-siano-4-isobutiloksifenil)-4-metil-5-tiazolkarboksilat, yang terdiri dari pengkristalan pada kondisi-kondisi yang dibatasi oleh suatu suhu spesifik dan suatu komposisi dari suatu pelarut campuran metanol dan air, dan polimorf-polimorf yang diperoleh dengan metode. Invensi ini lebih lanjut menyediakan suatu metode produksi polimorf-polimorf at au senyawa-senyawa amort lain dengan pengeringan suatu polimorf spesifik pada suatu tekanan yang dikurangi dengan pemanasan, dan polimorf-polimorf atau senyawa-senyawa amort lain yang diperoleh dengan metode.

- Metode pemotongan pohon berdiri di hutan rimba terdiri dari derek alat penggerak, yang lebih disukai derek dengan alat penggerak hidrolik, dengan lengan mesin derek (14) pada blok hutan, yang menjamin pohon yang dapat dipotong untuk diikatkan dalam lengan mesin, pemotongan dasar pohon, memindahkan potongan pohon itu menggunakan lengan mesin dan menempatkan potongan pohon diatas tanah dan potongan puncak potongan pohon. Menurut aspek lain puncak pohon yang dipotong pertama kali dan dipindahkan dengan menggunakan alat mencabut dengan lengan mesin derek. Derek digunakan untuk memindahkan puncak pohon atau puncak pohon yang dipotong pada dasarnya yang dibiarkan jatuh. Jalan utama, jalan pendorong dan jalur pencabutan yang dikonstruksikan di area kayu gelondongan. Total area dirusak oleh derek kurang dari 10% area yang akan dipotong. Sebagai kemungkinan lain, metode lain dari pohon yang dipotong di hutan rimba dengan membawa alat penggerak (20) dengan struktur lengan mesin derek (26) pada sebuah blok (102) pada hutan rimba, menjamin pohon kayu yang dipotong (70) pada kabel derek (40) diatas struktur lengan mesin (26), menstabilkan alat penggerak (20) dan pencabutan pohon kayu yang dipotong (70) pada crawer sedemikian rupa sehingga pohon yang dipotong dalam sudut kemiringan yang berkenaan dengan daun. Mesin pemotong hutan dari alat penggerak (20) dengan struktur lengan mesin (26) dan sebuah derek. Struktuk lengan dapat digulung (30) dengan cakar penjepit (34) yang dipasang secara memutar disepanjang struktur lengan mesin (26), dimana selama pencabutan dari mesin yang dipotong (70), struktur lengan yang dapat digulung (30) digunakan untuk menstabilkan alat penggerak (20). 

- Sesuai dengan rantai kancing, metode dan peralatan untuk membentuk ujung-ujungnya, elemen kancing berbentuk kumparan (11) sebagai elemen kancing linier (1) dipasang dan dijahit pada bagian tepi samping (5) dari sepasang pita kancing (2) dengan benang jahit (15) seperti benang pasang (4) sewaktu ulir inti (3) disisipkan melalui elemen kancing (1). Elemen kancing berbentuk kumparan (1) dipotong pada bagian kaki (22), yang masing-masingnya bersentuhan dengan pita kancing (2), di ujung elemen kancing (1), sehingga bagian ujung potongan (7) dibentuk. Bagian-bagian ujung potongan (7) ini didorong kedalam bagian tepi samping (5), dan kemudian, bagian kaki (22) dan bagian terbalik (23) darinya dilumer pita kancing (2) dengan pemanasan. Hasilnya, bentuk dari masing-masing ujung elemen kancing (1) distabilkan, sehingga kancing tarik hasilnya baik pada keamanannya.

- Media rekam yang menyimpan informasi tipe sambungan dan metode proses daerah yang rusak dalam media. Media rekam menyimpan informasi yang menunjukkan bahwa sambungan dipakai setelah daerah yang rusak, yang membedakan tipe sambungan yang terjadi dalam mode rekam inkremental umum dari tipe sambungan yang terjadi setelah daerah rusak. Daerah yang rusak dideteksi dan didaftar dalam daerah tertentu (data manajemen rekam (RMD) sebelum data pengguna direkam atau ketika data pengguna direkam dalam media rekam yang memiliki sejumlah unit rekam dasar berlanjut, seperti digital versatile disc-rewritable (DVD-RW) di mana rekaman dan reproduksi dapat dilakukan secara berulang-ulang. Sambungan tidak hanya dipakai dalam mode rekam inkremental atau dalam mode rekam tulis-tindih, tetapi sambungan juga dipakai ke daerah setelah daerah rusak yang didaftar dalam daerah kerusakan, yang menambah reliabilitas data pengguna. Dan lagi, sinyal uji seperti data penghubung direkam lebih dahulu dalam blok setelah daerah rusak yang dideteksi selama sertifikasi. Jika sinyal uji dideteksi setelah daerah rusak, data pengguna baru direkam setelah sejumlah blok kode koreksi kesalahan (ECC) yang mengikuti daerah rusak tanpa menggunakan sambungan yang mengurangi waktu untuk merekam data sambungan, yang merupakan keuntungan bagi perekam waktu riil.

- Suatu barang berdaya serap yang mempunyai suatu lapisan atas yang dapat menyerap cairan, suatu lapisan tahan bocor yang tidak dapat menyerap cairan, dan suatu lapisan berdaya serap penyimpan cairan yang diletakkan antara lapisan-lapisan tersebut, dimana lapisan berdaya serap mempunyai suatu bagian pengontrol bau yang mengandung (a) 20 sampai 80% berat serat hidrofilik atau busa hidrofilik yang khusus dan (b) suatu zat pengontrol bau, bagian pengontrol bau 9 terdiri dari suatu lapisan yang dibuat dari suatu campuran yang menyebar secara bersama-sama dari unsur (a) dan unsur (b) atau yang terdiri dari lapisan-lapisan yang secara terpisah berdekatan yang terdiri dari unsur (a) dan unsur (b).
Suatu piringan optik yang terdiri dari suatu daerah data dan suatu daerah manajemen, dimana daerah data tersebut menyimpan data audio pertama yang diperoleh dengan mengekspresikan informasi audio sesuai dengan atribut-atribut audio pertama dan data audio kedua yang diperoleh dengan mengekspresikan informasi audio sesuai dengan atribut-atribut audio kedua yang berbeda dari atribut-atribut audio pertama, dan daerah manajemen tersebut menyimpan informasi manajemen untuk memungkinkan reproduksi yang selektif dari salah satu data audio pertama dan data audio kedua tersebut.

- Suatu proses ekstraksi logam dari bijih atau konsentrat yang mengandung unsur-unsur nikel dan/atau kobalt dan logam-logam lain, yang terdiri dari tahap-tahap pemrosesan bijih atau konsentrat tersebut melalui pelindian asam bertekanan, pada 
Suatu sambungan pipa yang terdiri dari suatu anggota penguat berbentuk bulat yang diwujudkan di bagian dalam suatu bodi dasar sambungan pipa berongga dan berbentuk silinder yang dibuat dari suatu bahan elastis, dan anggota penguat tersebut ditunjang oleh suatu tuas penunjang yang diatur dapat lepas didalamnya dalam arah aksial, sehingga, sama jika suatu tekanan bagian dalam yang sesuai dengan suatu fluida dimuat ke dalam bodi dasar sambungan pipa, suatu tenaga reaksi yang besar dan menyebabkan suatu muatan yang tidak diharapkan pada saluran pipa tidak akan dihasilkan, dan karena ciri-ciri tersebut, masalah-masalah seperti penurunan flensa selama penyambungan dan suatu daerah temperatur yang sempit selama penggunaannya tidak pernah terjadi.

- Pengukuran-pengukuran langsung dari sejumlah partikel-partikel padat terlarut di dalam contoh cairan ditentukan dengan menggunakan pengukuran-pengukuran konduktifitas dan UV. Lebih khusus kepada sejumlah partikel-partikel padat terlarut di dalam sebuah air atau air kotor buangan sisa produksi dari proses pengadukan bubur kayu dan kertas ditentukan dengan melakukan penyinaran sekurang-kurangnya sebagian dari sebuah contoh cairan dengan sinar ultra violet dan secara berturut-turut melakukan pengukuran sebuah penyerapan cahaya pada contoh cairan. Lebih lanjut, konduktifitas dari contoh cairan diukur dan secara berturut-turut sebuah perhitungan jumlah dari kandungan terlarut di dalam contoh cairan dibuat dari sebuah hubungan pertama antara penyerapan yang diukur dari panjang gelombang pertama pada contoh cairan dan konduktifitas yang telah diukur dari contoh cairan dengan menggunakan sebuah pemroses yang diprogram agar dapat digunakan. 

- Penemuan berkaitan dengan tiazol-tiazol tersubstitusi agonis CCK kolesistokinin dari formula: dimana R1 adalah gugus fenil tersubstitusi, R2 adalah gugus yang dipilih dari CH2-R7, (CH2)2-R7, S-CH2-R7, CH2-S-R7 dan alkil (C5-C8) dengan R7 adalah suatu gugus sikloalkil(C5-C7), dan R3 adalah gugus dengan R8 adalah gugus (CH2)nR15 atau dan R15 adalah COOH atau COOalkil(C1-C4). Penemuan juga berkaitan dengan proses pembuatan komposisi farmasi yang mengandungnya dan penggunaannya untuk membuat obat-obatan. 

- Suatu produk makanan atau minuman dengan suatu sifat disinfeksi Helikobakter pilori dan/atau suatu sifat perlindungan terhadap infeksi dengan H. pilori yang terdiri dari sebagai ingradien yang efektif laktobasillus gasseri OLL 2716 (FERM BP-6999) dengan suatu potensi disinfeksi H. pilori yang tinggi. Produk makanan atau minuman yang dibuat dengan menggunakan bakterium asam laktat, seperti susu asam dan sejenisnya, adalah sesuai untuk penggunaan yang lama sebagai suatu produk makanan atau minuman dengan suatu sifat disinfeksi H. pilori dan/atau suatu sifat perlindungan terhadap infeksi dengan H. pilori. 

- Sebuah unit kirim/terima data yang menerima data digital yang telah dienkripsi yang didistribusikan melalui sebuah sistim distribusi musik elektronik dan merekam data digital pada sebuah media perekam primer. Data digital telah dienkripsi dalam sistim-sistim enkripsi yang berbeda menurut distributor-distributornya, dan mencakup informasi atribut yang menunjukkan sistim-sistim enkripsinya. Sistim enkripsi data digital yang telah diambilkan oleh unit pengambilan data ditetapkan oleh unit penetapan dan didekripsi oleh unit dekripsi yang sesuai. Unit perolehan informasi bawaan memperoleh informasi pengenalan media perekam sekunder atau aparatus main-ulang sesuai dengan apakah media perekam sekundernya dapat dipindahkan dari aparatus main-ulangnya. Unit penuju sistim enkripsi memilih satu diluar sejumlah-banyak unit enkripsi sesuai dengan informasi pengenalan yang telah diperolehnya. Unit enkripsi yang telah dipilih tersebut membuat kunci enkripsi sesuai dengan informasi pengenalan dan mengenkripsi data digital tersebut. Unit perekam merekam data digitalnya pada media perekam sekunder. Unit pelaporan mengenakan biaya sesuai dengan informasi pelaporan dalam informasi atributnya.

- Informasi banyak kata yang berdasarkan pada simbol-simbol banyak bit yang ditempatkan dalam rangkaian relatif berkaitan dengan suatu medium, dan diberi kode dengan suatu penyisipan yang berkaitan dengan kata dan kode perlindungan kesalahan yang berkaitan dengan kata, untuk memberikan petunjuk lokasi kesalahan melalui kelompok-kelompok banyak kata. Secara khusus, petunjuk-petunjuk menciptakan dalam kata-kata petunjuk protektivitas tinggi (BIS) yang disisipkan diantara kolom-kolom petunjuk dan juga kolom-kolom sinkronisasi yang dibentuk dari kelompok bit sinkronisasi. Kolom-kolom sinkronisas ditempatkan dimana kolom petunjuk ditempatkan relatif jarang. Petunjuk tersebut diarahkan pada kata-kata target protektivitas rendah (LDS) yang disisipkan dalam suatu cara yang pada dasarnya merata diantara kolom-kolom target yang membentuk kelompok-kelompok kolom yang berukuran sama diantara pengaturan periodik dari kolom-kolom petunjuk dan kolom-kolom sinkronisasi. 

- Suatu filter dengan struktur mikro untuk suatu fluida, filter tersebut mempunyai suatu inlet untuk fluida yang tidak tersaring dan outlet untuk fluida yang tersaring, filter tersebut terdiri dari: sejumlah tonjolan-tonjolan (7) yang disusun dalam setidaknya dua baris (3) secara berjajar dan yang menonjol keluar dari suatu pelat dasar (1) dan yang merupakan komponen terpadu dari pelat dasar, sejumlah jalur-jalur (8) antara tonjolan-tonjolan (7), dan suatu pelat tutup yang dapat dipasangkan pada pelat dasar untuk menutup atau melingkup tonjolan-tonjolan (7) dan jalur-jalur (8), dimana jalur-jalur tersebut membentuk sejumlah jalan lewat tembus dari inlet ke outlet, inlet termaksud mempunyai suatu celah inlet panjang (5) untuk fluida yang tidak tersaring, yang memanjang pada keseluruhan lebar filter dan yang tingginya adalah setinggi tonjolan-tonjolan (7) yang menonjol keluar dari pelat dasar, pada sisi inlet filter, dan outlet termaksud mempunyai suatu celah outlet panjang untuk fluida yang tersaring, yang memanjang pada keseluruhan lebar filter dan yang tingginya setinggi tonjolan-tonjolan (7) yang menonjol keluar dari pelat dasar, pada sisi outlet filter. Filter sesuai dengan penemuan ini tetap dapat bekerja bahkan bila sebagian filter tersumbat. Filter ini dapat digunakan misalnya dalam suatu atomiser dengan mana suatu aerosol dapat dihasilkan dari suatu fluida yang mengandung suatu obat.

- Suatu prosedur untuk untuk memulai proses pelelehan langsung untuk membuat besi dari bahan pasokan yang mengandung logam dalam suatu bejana dari bahan logam yang diungkapkan. Bejana tersebut dari jenis yang meliputi sejumlah pipa penyemprot/penghembus yang menginjeksikan bahan pasokan (11, 13). Prosedur pemulaian tersebut meliputi langkah-langkah: (a) memanaskan lebih dulu bejana; (b) memasok isian besi lelehan pada bejana dan membentuk rendaman lelehan dalam bejana; (c) memasok bahan dan fluks yang mengandung karbon ke rendaman lelehan dan menginjeksikan gas yang mengandung oksigen melalui satu atau lebih dari satu pipa penyemprot/penghembus injeksi bahan pasokan dan membakar karbon serta gas yang berasal dari rendaman (jika ada) serta kemudian memanaskan rendaman lelehan dan membangkitkan terak besi; dan (d) memasok bahan pasokan yang mengandung logam pada bejana sambil meneruskan pemasokan bahan dan fluks yang mengandung karbon serta menginjeksikan gas yang mengandung oksigen dan melelehkan bahan pasokan yang mengandung logam serta membuat besi lelehan dan kemudian menyempurnakan prosedur pemulaian tersebut.

- Penemuan ini berhubungan dengan bahan logam untuk onderdil elektronik, onderdil elektronik, aparatus elektronik, metode pemprosesan bahan logam, dan onderdil elektro-optik. Misalnya, penemuan ini diterapkan untuk panel tampilan kristal cair, berbagai peranti semikonduktor, papan jaringan kawat, onderdil chip dan sebagainya. Penemuan ini mengusulkan suatu bahan logam untuk onderdil elektronik yang dicirikan oleh resistifitas yang lebih rendah, stabilitas yang lebih tinggi dan kemampuan diproses yang lebih unggul daripada penemuan sebelumnya. Penemuan ini juga mengusulkan onderdil elektronik dan aparatus elektronik yang menggunakan bahan logam ini. Suatu bahan logam yang dapat dipakai adalah suatu aloi yang mengandung Ag sebagai komponen utama, 0,1 sampai 3% berat dari Pd dan total 0,1 sampai 3% berat dari unsur seperti A1. 

- Suatu aplikasi perangkat lunak pengendalian komunikasi digunakan dalam suatu peranti komunikasi pengguna yang memiliki suatu prosesor dan memori. Prosesor tersebut mengendalikan suatu penayang dan suatu peranti masukan pengguna. Suatu terminal komunikasi memindahkan serta menerima surat elektronik. Aplikasi perangkat-lunak pengendali komunikasi tersebut mencakup suatu aplikasi telepon yang tersimpan dalam memori tersebut, aplikasi telepon tersebut termasuk suatu database kartu bisnis yang menyimpan kartu-kartu bisnis berganda. Setiap kartu bisnis mengenali sifat-sifat suatu pemasok kartu tertentu terhadap mana surat elektronik akan dikirimkan kepadanya atau diterima darinya. Satu atau lebih kartu-kartu bisnis tersebut termasuk suatu unsur kartu bisnis yang berkaitan yang dinyatakan oleh suatu rutinitas perangkat-lunak penyalur yang mengendalikan bagaimana surat elektronik dihubungkan diantara pengguna dan pemasok tertentu. Suatu aplikasi penyuratan mengawali komunikasi untuk memindahkan atau menerima surat elektronik. Aplikasi telepon tersebut serta aplikasi penyuratan tersebut menentukan apakah suatu unsur kartu bisnis berkaitan dengan suatu kartu bisnis dari suatu pemasok terhadap mana surat elektronik akan dikirimkan padanya atau diterima darinya melalui aplikasi pemutaran telepon, dan sebagai tanggapan terhadapnya menerapkan rutinitas perangkat-lunak penyalur untuk mengendalikan cara surat elektronik tersebut harus dihubungkan.

- Partikel-partikel rekayasa disediakan untuk mengangkut zat bioaktif ke dalam saluran pernapasan seorang pasien. Partikel-partikel tersebut dapat dipakai dalam bentuk serbuk kering atau dispersi stabil yang mengandung fasa sinambung tidak berair. Pada perwujudan-perwujudan yang disukai, partikel-partikel ini dapat dipakai dengan peranti inhalasi seperti inhalator serbuk kering, inhalator dengan dosis terukur atau nebulisator. 

- Suatu protease alkalin yang mempunyai sifat-sifat berikut; suatu gen yang mengkodekan sama, suatu mikroorganisme yang menghasilkan sama; dan komposisi pencuci yang mengandung sama; (i) yang beraksi pada kisaran pH yang luas 4 sampai 13 mencapai, pada pH 6 sampai 12, 80% atau lebih aktivitas pada nilai pH optimum; (ii) jika diperlukan pada 40oC selama 30 menit, menjadi stabil pada kisaran nilai pH 6 sampai 11; (iii) yang mempunyai titik isoelektrik sekitar 8,9 sampai 9.1; dan (iv) yang mempunyai aktivitas pencerna kasein yang tidak ditunjukkan oleh asam oleat. Protease alkalin dari penemuan ini sangat stabil untuk bermacam-macam bahan aktif permukaan dan asam lemak, dan menunjukkan stabilitas yang tinggi untuk bahan-bahan pengoksidasi, dan oleh karena itu bermanfaat sebagai suatu enzim untuk digunakan dalam detergen untuk pencuci piring otomatik dan detergen pencuci pakaian, keduanya mengandung komponen-komponen pemutih.

- Susunan kristal bentuk banyak dari bentuk I (-) -4- [4- [4-[4- [ [ (2R-cis) -5- (2, 4-diflorofenil) tetrahidro-5- (1H-1, 2, 4triazol-1-ilmetil) furan-3-il] metoksi] fenil-1-piperazinil] fenil-2, 4-dihidro-2- [ (S) -1-etil-2 (S) hidroksilpropil ] -3H- 1, 2, 4 - triazol - 3 -one yang ditampilkan oleh formula I, komposisi farmasi mengandung bentuk banyak demikian dan menjelaskan metode penggunaannya untuk mengobati infeksi jamur pada binatang menyusui.

- Elemen kancing bentuk lilitan (2) terdiri dari kepala perangkai (4) yang menonjol ke kedua sisi, bagian kaki atas/bawah (5, 6) yang berdekatan dengan kepala perangkai (4) dan bagian penghubung (7) untuk menghubungkan bagian kaki atas dan bawah (5, 6). Dengan menyediakan bagian tanjakan (8) pada pusat bagian kaki atas (5), bagian elemen kancing (2) pada sisi kepala perangkai (4) dibentuk tebal sedangkan bagiannya pada sisi bagian penghubung (7) dibentuk tipis. Ruang perangkaian (9) disediakan diantara bagian kaki atat dan bawah (5, 6). Bagian tonjolan (10) yang ditonjolkan kedalam ruang perangkaian (9) disediakan di belakang bagian tanjakan (8) pada bagian kaki atas (5). Bagian landai (12) dibentuk sedemikian hingga ruang perangkaian (9) diperluas dari dalam bagian atas kepala perangkai (4) ke bagian dasar (11) bagian tonjolan (10). Ulir inti (28) disisipkan diantara bagian kaki atas dan bawah (5, 6) dan dijahit dengan menggunakan benang jahit (15) dengan setik jahitan rantai berulir banyak sebagai benang pasang (14), sedemikian hingga tepi samping ulir inti (28) ditonjolkan kearah kepala perangkai (4). Dalam merangkaikan, kepala perangkai (4) dimungkinkan untuk disisipkan dengan cepat sepanjang bagian landai (12) dan penyisipan elemen perangkai pasangan yang lebih dicegah oleh bagian tonjolan (10) dan ulir inti (28) dengan maksud untuk menstabilkan perangkaian. Jadi, kancing tarik linier memungkinkan operasi perangkaian yang lancar dan cepat. 

- Invensi ini berhubungan dengan senyawa-senyawa antimikroba baru pada Formula (1) dimana X, R1, R3, R5, R6 dan R8 didefinisikan dalam klaim-klaim, dan dengan isomer-isomer optis, diastereomer-diastereomer atau enantiomer-enantiomer mereka, dan juga garam-garam yang dapat diterima secara farmasi, hidrat-hidrat, dan ester-ester, amida-amida, imida-imidanya yang dapat dihidrolisa secara biologis, dan dengan komposisi-komposisi dan penggunaan-penggunaan senyawa-senyawa seperti tersebut. Invensi tersebut juga berhubungan dengan senyawa-senyawa yang diderivatisasi dari senyawa-senyawa tersebut yang memiliki kegunaan-kegunaan antimikroba.

- Suatu metode untuk mengurangi sebagian besar batasan dosis setiap hari yang diperlukan untuk mengontrol rasa sakit pasien kira-kira 90% yang dijelaskan dimana formulasi sediaan oral padatan pelepasan terkontrol mempunyai dari sekitar 10 hingga 40 mg oksikodon atau garamnya yang dipakai oleh pasien. Formulasi memberikan konsentrasi rata-rata plasma oksikodon maksimum dari sekitar 6 hingga 60 ng/ml dari rata-rata 2 hingga 4,5 jam setelah pemakaian, dan konsentrasi rata-rata plasma minimum dari sekitar 3 hingga 30 ng/ml dari 10 hingga 14 jam setelah pemakaian "q12h" diulangi (yakni, setiap 12 jam) melalui kondisi keadaan tetap. 

- Diungkapkan pembangkit kunci perluasan, satuan penyandian/pemecahan sandi, dan media penyimpanan, dimana sebagai masing-masing fungsi transformasi kunci, proses transformasi dilakukan oleh kotak S (tabel substitusi) berdasarkan kunci pertama yang diperoleh dari kunci masukan, dan penambah menghitung salah satu kunci perluasan yang cocok berdasarkan nilai yang diperoleh dengan menggeser hasil transformasi kotak S ke kiri, dan kunci kedua yang diperoleh dari kunci masukan. (Putusan Komisi Banding tanggal 20 Januari 2005)

- Kantong yang berisi benda (10) meliputi sepasang Iembaran film (774, 11b) yang diletakkan satu di atas yang Iainnya dan memiliki tepi-tepi periferal (18, (19a, 19b), 21) yang disegel-panas. Suatu bagian mulut (12) dibentuk di lembaran-Iembaran (11a, 11b), dan garis-garis pemotongan (13) disediakan di bagian mulut (12). Suatu rusuk tonjolan (17) disediakan di permukaan bagian dalam dari setidaknya salah satu lembaran (11a, 11b), yang membentang dan memotong garis-garis pemotongan (13). Rusuk tonjolan (17) membentuk suatu saluran pembuangan (20) .

- Penemuan ini digambarkan sebagai suatu proses untuk isomerisasi campuran non-kesetimbangan pada xilena dan etilbenzena dengan menggunakan suatu katalis yang terdiri atas zeolit, logam golongan platinum dan suatu pengikak aluminofosfat atau silika, yang memberikan hasil dalam suatu hasil para-xilena yang lebih besar pada kondisi yang lebih disukai yang dibandingkan pada proses yang diketahui dalam bidang ini.

- Formula vaksin babi terhadap penyebab penyakit reproduksi dan/atau penyebab penyakit saluran pernafasan, terdiri dari sekurang-kurangnya tiga valensi vaksin polinukleutida, masing-masing terdiri dari plasmid terpadu, sehingga mencerminkan dalam tubuh makhluk hidup dalam sel-sel inang, gen dengan satu valensi penyebab penyakit babi, valensi ini dipilih dari dua kelompok, terdiri dari virus penyakit dari Aujeszky, virus flu babi, virus penyakit aneh babi, virus parvo virosis, virus pesti virosis, dan bakteri penyebab bagi aktinobaksil, plasmid terdiri dari untuk setiap valensi satu atau lebih dari gen dipilih dari kelompok, terdiri dari gB dan gD untuk virus penyakit dari Aujeszky, HA, NP dan N untuk virus flu babi, E, N, dan ORF 3, N untuk virus penyakit aneh babi, VP 2 untuk virus par-vo virosis, E1, E2 untuk virus pesti virosis dan apxI, apxII dan apxIII untuk virus aktinobaksil.

- Sistem komunikasi spektrum menyebar akses berganda mengolah sejumlah sinyal informasi yang diterima oleh Stasiun Pembawa Radio (RCS) pada kanal telekomunikasi untuk transmisi serentak pada kanal frekuensi radio (RF) sebagai sinyal divisi kode berganda (CDM) ke kelompok Satuan Pelanggan (SU). RCS menerima sinyal permintaan panggilan yang menghubungkan sinyal informasi kanal telekomunikasi, dan sinyal identifikasi pemakai yang mengidentifikasi pemakai dimana permintaan panggilan dan sinyal informasi dialamatkan. RCS meliputi sejumlah modem Akses Berganda Divisi Kode (CDMA), satu menyediakan sinyal kode pilot global, dan modem menyediakan sejumlah sinyal kode pesan untuk yang sama dengan sinyal pilot global. Dalam hubungan dengan sinyal tugas kanal, setiap modem menggabungkan sinyal informasi dengan sinyal kode pesan untuk menyediakan sinyal yang diolah CDM. RCS meliputi pengontrol kanal sistem yang dirangkaikan untuk menerima panggilan jarak jauh. RCS yang menyediakan sinyal tugas kanal yang peka terhadap sinyal identifikasi pemakai. Pengirim RF dihubungkan dengan semua modem untuk menggabungkan sinyal yang diolah CDM dengan sinyal kode pilot global untuk menghasilkan sinyal CDM. Pengirim RF juga mengarahkan sinyal pembawa dengan sinyal CDM dan mengirim sinyal pembawa yang diarahkan lewat kanal komunikasi RF ke SU. Setiap SU peka terhadap sinyal identifikasi pemakai yaitu modem CDMA yang juga disinkronkan ke sinyal pilot global. Modem CDMA menyempitkan sinyal CDM untuk mendapatkan sinyal informasi, dan menyediakan sinyal informasi ke pemakai. Sistem tersebut meliputi metode pengontrolan energi loop tertutup untuk menjaga tingkat energi kirim minimum untuk RCS dan SU, dan pengaturan kapasitas sistem untuk menjaga sejumlah SU aktif maksimum untuk kinerja sistem yang meningkat.

- Sistem komunikasi spektrum menyebar akses berganda mengolah sejumlah sinyal informasi yang diterima oleh Stasiun Pembawa Radio (RCS) pada kanal telekomunikasi untuk transmisi serentak pada kanal frekuensi radio (RF) sebagai sinyal divisi kode berganda (CDM) ke kelompok Satuan Pelanggan (SU). RCS menerima sinyal permintaan panggilan yang menghubungkan sinyal informasi kanal telekomunikasi, dan sinyal identifikasi pemakai yang mengidentifikasi pemakai dimana permintaan panggilan dan sinyal informasi dialamatkan. RCS meliputi sejumlah modem Akses Berganda Divisi Kode (CDMA), satu menyediakan sinyal kode pilot global, dan modem menyediakan sejumlah sinyal kode pesan untuk yang sama dengan sinyal pilot global. Dalam hubungan dengan sinyal tugas kanal, setiap modem menggabungkan sinyal informasi dengan sinyal kode pesan untuk menyediakan sinyal yang diolah CDM. RCS meliputi pengontrol kanal sistem yang dirangkaikan untuk menerima panggilan jarak jauh. RCS yang menyediakan sinyal tugas kanal yang peka terhadap sinyal identifikasi pemakai. Pengirim RF dihubungkan dengan semua modem untuk menggabungkan sinyal yang diolah CDM dengan sinyal kode pilot global untuk menghasilkan sinyal CDM. Pengirim RF juga mengarahkan sinyal pembawa dengan sinyal CDM dan mengirim sinyal pembawa yang diarahkan lewat kanal komunikasi RF ke SU. Setiap SU peka terhadap sinyal identifikasi pemakai yaitu modem CDMA yang juga disinkronkan ke sinyal pilot global. Modem CDMA menyempitkan sinyal CDM untuk mendapatkan sinyal informasi, dan menyediakan sinyal informasi ke pemakai. Sistem tersebut meliputi metode pengontrolan energi loop tertutup untuk menjaga tingkat energi kirim minimum untuk RCS dan SU, dan pengaturan kapasitas sistem untuk menjaga sejumlah SU aktif maksimum untuk kinerja sistem yang meningkat.

- Sistem komunikasi spektrum menyebar akses berganda mengolah sejumlah sinyal informasi yang diterima oleh Stasiun Pembawa Radio (RCS) pada kanal telekomunikasi untuk transmisi serentak pada kanal frekuensi radio (RF) sebagai sinyal divisi kode berganda (CDM) ke kelompok Satuan Pelanggan (SU). RCS menerima sinyal permintaan panggilan yang menghubungkan sinyal informasi kanal telekomunikasi, dan sinyal identifikasi pemakai yang mengidentifikasi pemakai dimana permintaan panggilan dan sinyal informasi dialamatkan. RCS meliputi sejumlah modem Akses Berganda Divisi Kode (CDMA), satu menyediakan sinyal kode pilot global, dan modem menyediakan sejumlah sinyal kode pesan untuk yang sama dengan sinyal pilot global. Dalam hubungan dengan sinyal tugas kanal, setiap modem menggabungkan sinyal informasi dengan sinyal kode pesan untuk menyediakan sinyal yang diolah CDM. RCS meliputi pengontrol kanal sistem yang dirangkaikan untuk menerima panggilan jarak jauh. RCS yang menyediakan sinyal tugas kanal yang peka terhadap sinyal identifikasi pemakai. Pengirim RF dihubungkan dengan semua modem untuk menggabungkan sinyal yang diolah CDM dengan sinyal kode pilot global untuk menghasilkan sinyal CDM. Pengirim RF juga mengarahkan sinyal pembawa dengan sinyal CDM dan mengirim sinyal pembawa yang diarahkan lewat kanal komunikasi RF ke SU. Setiap SU peka terhadap sinyal identifikasi pemakai yaitu modem CDMA yang juga disinkronkan ke sinyal pilot global. Modem CDMA menyempitkan sinyal CDM untuk mendapatkan sinyal informasi, dan menyediakan sinyal informasi ke pemakai. Sistem tersebut meliputi metode pengontrolan energi loop tertutup untuk menjaga tingkat energi kirim minimum untuk RCS dan SU, dan pengaturan kapasitas sistem untuk menjaga sejumlah SU aktif maksimum untuk kinerja sistem yang meningkat.

- Sistem komunikasi spektrum menyebar akses berganda mengolah sejumlah sinyal informasi yang diterima oleh Stasiun Pembawa Radio (RCS) pada kanal telekomunikasi untuk transmisi serentak pada kanal frekuensi radio (RF) sebagai sinyal divisi kode berganda (CDM) ke kelompok Satuan Pelanggan (SU). RCS menerima sinyal permintaan panggilan yang menghubungkan sinyal informasi kanal telekomunikasi, dan sinyal identifikasi pemakai yang mengidentifikasi pemakai dimana permintaan panggilan dan sinyal informasi dialamatkan. RCS meliputi sejumlah modem Akses Berganda Divisi Kode (CDMA), satu menyediakan sinyal kode pilot global, dan modem menyediakan sejumlah sinyal kode pesan untuk yang sama dengan sinyal pilot global. Dalam hubungan dengan sinyal tugas kanal, setiap modem menggabungkan sinyal informasi dengan sinyal kode pesan untuk menyediakan sinyal yang diolah CDM. RCS meliputi pengontrol kanal sistem yang dirangkaikan untuk menerima panggilan jarak jauh. RCS yang menyediakan sinyal tugas kanal yang peka terhadap sinyal identifikasi pemakai. Pengirim RF dihubungkan dengan semua modem untuk menggabungkan sinyal yang diolah CDM dengan sinyal kode pilot global untuk menghasilkan sinyal CDM. Pengirim RF juga mengarahkan sinyal pembawa dengan sinyal CDM dan mengirim sinyal pembawa yang diarahkan lewat kanal komunikasi RF ke SU. Setiap SU peka terhadap sinyal identifikasi pemakai yaitu modem CDMA yang juga disinkronkan ke sinyal pilot global. Modem CDMA menyempitkan sinyal CDM untuk mendapatkan sinyal informasi, dan menyediakan sinyal informasi ke pemakai. Sistem tersebut meliputi metode pengontrolan energi loop tertutup untuk menjaga tingkat energi kirim minimum untuk RCS dan SU, dan pengaturan kapasitas sistem untuk menjaga sejumlah SU aktif maksimum untuk kinerja sistem yang meningkat.

- Sistem komunikasi spektrum menyebar akses berganda mengolah sejumlah sinyal informasi yang diterima oleh Stasiun Pembawa Radio (RCS) pada kanal telekomunikasi untuk transmisi serentak pada kanal frekuensi radio (RF) sebagai sinyal divisi kode berganda (CDM) ke kelompok Satuan Pelanggan (SU). RCS menerima sinyal permintaan panggilan yang menghubungkan sinyal informasi kanal telekomunikasi, dan sinyal identifikasi pemakai yang mengidentifikasi pemakai dimana permintaan panggilan dan sinyal informasi dialamatkan. RCS meliputi sejumlah modem Akses Berganda Divisi Kode (CDMA), satu menyediakan sinyal kode pilot global, dan modem menyediakan sejumlah sinyal kode pesan untuk yang sama dengan sinyal pilot global. Dalam hubungan dengan sinyal tugas kanal, setiap modem menggabungkan sinyal informasi dengan sinyal kode pesan untuk menyediakan sinyal yang diolah CDM. RCS meliputi pengontrol kanal sistem yang dirangkaikan untuk menerima panggilan jarak jauh. RCS yang menyediakan sinyal tugas kanal yang peka terhadap sinyal identifikasi pemakai. Pengirim RF dihubungkan dengan semua modem untuk menggabungkan sinyal yang diolah CDM dengan sinyal kode pilot global untuk menghasilkan sinyal CDM. Pengirim RF juga mengarahkan sinyal pembawa dengan sinyal CDM dan mengirim sinyal pembawa yang diarahkan lewat kanal komunikasi RF ke SU. Setiap SU peka terhadap sinyal identifikasi pemakai yaitu modem CDMA yang juga disinkronkan ke sinyal pilot global. Modem CDMA menyempitkan sinyal CDM untuk mendapatkan sinyal informasi, dan menyediakan sinyal informasi ke pemakai. Sistem tersebut meliputi metode pengontrolan energi loop tertutup untuk menjaga tingkat energi kirim minimum untuk RCS dan SU, dan pengaturan kapasitas sistem untuk menjaga sejumlah SU aktif maksimum untuk kinerja sistem yang meningkat.

- Sistem komunikasi spektrum menyebar akses berganda mengolah sejumlah sinyal informasi yang diterima oleh Stasiun Pembawa Radio (RCS) pada kanal telekomunikasi untuk transmisi serentak pada kanal frekuensi radio (RF) sebagai sinyal divisi kode berganda (CDM) ke kelompok Satuan Pelanggan (SU). RCS menerima sinyal permintaan panggilan yang menghubungkan sinyal informasi kanal telekomunikasi, dan sinyal identifikasi pemakai yang mengidentifikasi pemakai dimana permintaan panggilan dan sinyal informasi dialamatkan. RCS meliputi sejumlah modem Akses Berganda Divisi Kode (CDMA), satu menyediakan sinyal kode pilot global, dan modem menyediakan sejumlah sinyal kode pesan untuk yang sama dengan sinyal pilot global. Dalam hubungan dengan sinyal tugas kanal, setiap modem menggabungkan sinyal informasi dengan sinyal kode pesan untuk menyediakan sinyal yang diolah CDM. RCS meliputi pengontrol kanal sistem yang dirangkaikan untuk menerima panggilan jarak jauh. RCS yang menyediakan sinyal tugas kanal yang peka terhadap sinyal identifikasi pemakai. Pengirim RF dihubungkan dengan semua modem untuk menggabungkan sinyal yang diolah CDM dengan sinyal kode pilot global untuk menghasilkan sinyal CDM. Pengirim RF juga mengarahkan sinyal pembawa dengan sinyal CDM dan mengirim sinyal pembawa yang diarahkan lewat kanal komunikasi RF ke SU. Setiap SU peka terhadap sinyal identifikasi pemakai yaitu modem CDMA yang juga disinkronkan ke sinyal pilot global. Modem CDMA menyempitkan sinyal CDM untuk mendapatkan sinyal informasi, dan menyediakan sinyal informasi ke pemakai. Sistem tersebut meliputi metode pengontrolan energi loop tertutup untuk menjaga tingkat energi kirim minimum untuk RCS dan SU, dan pengaturan kapasitas sistem untuk menjaga sejumlah SU aktif maksimum untuk kinerja sistem yang meningkat.

- Suatu alat (10) yang diberikan untuk menyaring kontaminan-kontaminan tertentu dalam suatu media yang dapat mengalir. Alat (10) tersebut terdiri dari bagian bodi berongga (12) yang memiliki ujung bukaan pertama dan ujung bukaan kedua yang berlawanan dengan ujung pertama termaksud, suatu bagian mangkuk (18) yang memiliki suatu lubang tembus dan bagian mangkuk (18) tersebut di adaptasi agar terpasang dengan dapat dipindah-pindahkan pada ujung pertama termaksud untuk media yang dapat mengalir tersebut untuk mengalir melalui lubang termaksud menuju rongga dari bagian bodi (12) dan suatu massa (52) dari bahan serat tekstil disisir atau tak dipintal ditempatkan di dalam rongga tersebut dan di dalam jalur aliran dari media yang dapat mengalir tersebut sehingga kontaminan-kontaminan tersebut terperangkap di dalam massa dan media yang dapat mengalir yang terbebas dari kontaminan-kontaminan termaksud dapat mengalir keluar dari bagian bodi (12) melalui bukaan kedua termaksud.

- Gabungan bergalur yang sangat tahan terhadap gaya putar berlebih dan pemampatan yang terdiri dari bagian bergalur dalam permukaan internalnya yang disebut bagian penerima yang menggabungkan bagian bergalur dalam permukaan eksternalnya yang disebut bagian yang diterima. Gabungan di antara ujung yang diterima dan penerima dihasilkan melalui permukaan bergalur. Bila bagian-bagian dirangkai seluruhnya, satu permukaan yang diorientasikan secara aksial dalam ujung bebas dari satu dari bagian-bagian tersebut yang disebut hidung menekan terhadap permukaan yang sesuai dalam bagian yang lain yang disebut bahu dari gaya putar tersebut. Bahu ini terdiri dari dua permukaan, dan bagian kedua yang dipotong dan berbentuk kerucut dengan sudut B dan dengan sumbu dari pipa yang ditempatkan diantara permukaan pertama dan permukaan silinder internal dari bagian penerima. Geometri ini meningkatkan ketahanannya terhadap kerja gaya putar yang berlebihan, tanpa harus menambah permukaan kontak yang bersih di antara permukaan anuler yang diarahkan secara aksial dari nose dan permukaan yang berhubungan dari bahu bagian kedua.

- Blok peredam getaran (46) dipasang pada rangka kendaraan (11) dengan memasang bagian tonjolan (46b) blok peredam getaran (46) untuk menekan getaran rangka kendaraan (11) pada komponen bawah (52), dengan memampatkan dasar (46c) blok peredam getaran (46) dengan komponen atas (51), dan kemudian dengan menggabungkan bagian flensa (51c, 51c) komponen atas dan bawah (51) dan (52) dengan bagian flensa (52c, 52c). Jika komponen atas dan bawah digabungkan dengan misalnya proses pengelasan titik, pemampatan blok peredam getaran dan penerapan tekanan pengelasan titik dilakukan pada arah yang sama, dan karena itu, tekanan pengelasan titik dapat digunakan juga untuk pemampatan blok peredam getaran. Dengan demikian, tidak ada alat khusus yang diperlukan untuk memampatkan blok peredam getaran. Karena itu, mungkinlah untuk menggunakan perlengkapan dengan struktur yang sederhana untuk membuat rangka kendaraan yang mempunyai struktur peredam getaran dan untuk mempermudah pembuatan rangka kendaraan yang mempunyai struktur peredam getaran.

- Penemuan ini menyediakan satu campuran dari celupan-celupan yang terdiri dari satu atau lebih bahan-bahan celupan monoazo yang sesuai dengan formula umum (1) dan satu atau lebih bahan-bahan celupan monoazo yang sesuai dengan formula (2) dimana R1, R2, R3, R4, R5, R6, Y1, Y2 dan M didefinisikan seperti yang diberikan dalam klaim 1, metode-metode untuk menyiapkan campuran-campuran celupan tadi dan metode-metode untuk mencelup bahan-bahan yang mengandung-hidroksi dan/atau karboksamido dengan menggunakan campuran-campuran celupan tadi.

- Suatu rakitan pipa-dalam-pipa. Suatu kopling digunakan untuk menyambung ujung-ujung pipa dalam. Pipa dalam tersebut disentralisasi di dalam pipa dalam guna memberikan tahanan aksial namun hambatan minimum melintas ke sumbu rakitan tersebut. Ini memberikan fleksibilitas pipa dalam yang memadai dalam mengakomodasi toleransi yang diperlukan supaya kopling dapat digunakan. Pipa dalam tersebut dapat disentralisasi di dalam pipa luar tersebut dengan menggunakan busa yang disuntikkan di antara pipa dalam tersebut dan pipa luar tersebut dan suatu selongsong jaringan berombak yang mengelilingi ujung-ujung pipa dalam tersebut. Pipa dalam tersebut dapat pula disentralisasi di dalam pipa luar tersebut dengan menggunakan dinding antara jaringan berombak yang mengepas di sekeliling pipa dalam tersebut dan di dalam pipa luar tersebut.

- Imidazotriazinon-imidazotriazinon tersubstitusi 2-fenil yang mempunyai radikal-radikal alkil pendek, tidak bercabang dalam posisi 9 dibuat dari imidazotriazinon-2-fenil dengan klorosulfonasi dan berikutnya reaksi dengan amina-amina. Senyawa-senyawa penghambat fosfodiesterase-fosfodiesterase yang memetabolisme cGMp dan sesuai untuk penggunaan sebagai senyawa-senyawa aktif dalam sedian-sediaan farmasi, untuk pengobatan pada gangguan-gangguan kardiovaskular dan serebrovaskular dan/atau gangguan dari sistem dari urogenital, terutama untuk pengobatan disfungsi erektil.

- Diungkapkan unit pemompa bertiang melengkung, di mana penopang dan pengurang kecepatan kedua-duanya dipasang di dasar, dudukan tiang dipasang di ujung atas penopang, dan perangkat perangkai dihubungkan lewat salah satu ujungnya ke tiang lintang yang dipasang secara tetap pada tiang berjalan dan dihubungkan ke engkol di ujung yang lain yang menghubungkan pengurang kecepatan dengan pengimbang engkol, dengan ciri bahwa ujung belakang tiang berjalan dibuat melengkung dan memiliki beban pengimbang yang dipasang di bagian belakangnya.

- Penemuan ini berhubungan dengan suatu proses pembuatan campuran diastereomerik dari senyawa-senyawa eter siklik piperidinilaminometil trifluorometil dari formula Ia dan Ib: dan garamnya yang dapat diterima secara farmasi, di mana adalah alkil (C1-C6); R2 adalah alkil (C1-C6), halo alkil (C1-C6) atau fenil atau fenil tersubstitusi; R3 adalah hidrogen atau halo; m adalah nol, satu, atau dua; dan di mana campuran tersebut sangat diperkaya dengan adanya senyawa formula Ia, dan dengan proses-proses baru untuk pembuatan dan pemurnian senyawa-senyawa perantara yang berguna pada pembuatan senyawa-senyawa formula Ia dan Ib.

- Penemuan ini berhubungan dengan piranti sakelar bagian kontak dari pemutus rangkaian yang dapat menjamin kepercayaan operasi dengan menahan distorsi dari setiap bagian konstruksi dalam operasi dari pemutus rangkaian, dan memasang dengan mudah bagian tambahan untuk melakukan berbagai fungsi, penemuan ini terdiri dari tuas sakelar yang dipasang untuk berputar di antara posisi penetrasi dan posisi sumbatan dari bagian kontak tetap dan bagian kontak yang dapat bergerak, pegas sumbatan yang digabungkan ke tuas sakelar, roda operasi yang dipasang pada sisi dari tuas sakelar sedemikian sehingga berputar, sarana perggerak roda operasi untuk memutar roda operasi, lengan operasi yang dipasang pada sisi dari roda operasi sedemikian sehingga berputar, penghubung elektrik yang disisipkan di antara roda operasi dan lengan operasi, pegas penetrasi yang digabungkan ke lengan operasi, lengan lesat yang digabungkan ke poros putar dari tuas sakelar, grendel lesat untuk mencegah tuas sakelar dari berputar ke posisi mati, grendel penetrasi yang dipasang pada sisi dari roda operasi, dan sarana transmisi yang ditempatkan di antara lengan operasi dan tuas sakelar.

- Invensi ini berkaitan dengan proses pembuatan kopolimer lateks karet alam-metil metakrilat atau kopolimer lateks karet alam stiren. Lateks pekat dengan kadar karet kering antara 40 sampai dengan 70 dibubuhi emulsi metil metakrilat atau stiren pada kadar antara 0,1 psk sampai dengan 300 kps (per seratus bagian berat karet, kemudian campuran diiradiasi dengan sinar gamma atau berkas elektron pada dosis 1 kGy hingga 100 kGy, setelah itu ditambahkan bahan pelengket berupa sodium akrilat, sodium alginate, ammonium alginate, atau karboksi metil selulosa sebanyak 0,1 hingga 10 % berat campuran. Produknya berupa perekat yang dapat digunakan sebagai perekat panel kayu dan sepatu kanvas.

- Sasaran dari penemuan ini adalah untuk memberikan suatu motor listrik putar jenis magnet permanen sebagai perangkat stater generator dengan mana torsi penggerak yang tinggi dapat diperoleh apabila berfungsi sebagai motor stater di mana torsi yang digerakkan dapat ditekan serendah mungkin saat berfungsi sebagai generator. Untuk mencapai sasaran di atas, suatu motor listrik putar jenis magnet permanen yang mencakup stator dalam (50) dan lilitan stator (53) pada stator tersebut, dan yok rotor yang berbentuk bulat panjang (61) yang mencakup sejumlah magnet-magnet permanen (62) ditempatkan di sepanjang arah keliling dapat dapat berputar di sekeliling stator dalam (50) dan dimana yok rotor (61) memiliki bagian kutub-balik (613) di antara tiap magnet-magnet permanen (62) yang berdekatan, dibangun sedemikian rupa sehingga celah-celah pertama (612), celah-celah kedua (614) diberikan pada bagian di antara tiap magnet-magnet permanen (62) dan yok rotor (61).

- Sebuah sistem telemetering pemakaian daya listrik, yang terdiri atas: penggandeng opto dan pengalih (8), yang dipasang tetap pada KWH meter pelanggan sehingga dapat mendeteksi lubang piringan logam KWH meter tersebut yang berarti suatu data cacahan-naik dan mengirimkan data tersebut melalui kabel ke modul pencacah (1); modul pencacah (1), yang meliputi: pengontrol mikro (9) yang di dalamnya terdapat serpih memori (10) untuk menyimpan data cacahan-naik dan pengalih opto (8), trimancar radio (12) yang akan menerima dan memancarkan sinyal data dalam bentuk gelombang radio, trimancar merah infra (15) yang akan menerima dan memancarkan data dalam bentuk gelombang merah infra, jalur (13) yang merupakan jalur sinyal yang berasal dari pengontrol mikro (9) ke trimancar radio (12) / atau ke trimancar merah infra (15) atau sebaliknya, terminal (14) untuk menyalurkan data awal angka cacahan KWH meter melalui jalur (13) ke pengontrol mikro (9), pengalih merah infra penerima (16) menerima data dari modul pencatat (3), dan pengalih merah infra pemancar (17) untuk mengalirkan data ke modul pencatat (1); dan modul pencatat (3), yang terdiri atas: pengontrol mikro (26) yang di dalamnya terdapat pula memori (27) menyimpan data, trimancar radio (22) yang dilengkapi dengan antena (21) yang akan menerima dan memancarkan sinyal data dalam bentuk gelombang radio, trimancar merah infra (23) yang akan menerima dan memancarkan sinyal data dalam bentuk gelombang merah infra, pengalih merah infra pemancar (20) untuk meneruskan sinyal merah infra ke modul pencacah (1), pengalih merah infra penerima (19) untuk menerima sinyal merah infra dari modul pencacah (1) dan jalur (24) yang merupakan jalur sinyal yang berasal dari pengontrol mikro (26) ke trimancar radio (22) / atau ke trimancar merah infra (23), atau sebaliknya. Memori (10), (27) yang digunakan dalam sistem tersebut adalah memori jenis tak lenyap. Sistem tersebut dilengkapi pula dengan saklar pemindah (30), (31) sebagai sarana untuk mengubah ragam pendeteksian.

- Sebuah mesin cuci pakaian (I) yang bekerja dengan sistem pres (tekanan) pada waktu pencucian, memiliki bodi mesin cuci (11) yang dilengkapi dengan sebuah penutup (12) dan diberi engsel (13). Di dalam bodi mesin cuci (II) terdapat sebuah bak (14) tempat menampung air (15) yang terlebih dahulu telah diberi deterjen. Bak (14) ini kemudian dipakai untuk merendam pakaian-pakaian (16) yang akan dicuci. Mesin cuci pakaian (1) menurut penemuan ini, dibagian bawahnya juga dilengkapi dengan sebuah motor listrik (17) yang berfungsi sebagai alat pendorong pengepresan, sehingga proses pengepresan dapat berlangsung. Motor listrik (17) ini akan memutar roda gigi (18) yang memiliki mur (19) ditengah-tengahnya, untuk mengatur gerakan poros berulir (20) naik/turun pada waktu proses pengepresan/pelepasan terjadi.

- Suatu peralatan topi pelek kendaraan bermotor yang berfungsi sebagai penahan, penguat pelek yang retak yang disesuaikan dengan pelek kendaraan khususnya kendaraan yang berbeban berat dan dicirikan dengan bodi melingkar sesuai dengan lingkaran pelek dengan lubang utama di bagian tengah topi pelek dengan diameter sedikit lebih besar dari diameter tromol roda, di sebelah luar lubang-lubang untuk baut roda ke arah mengelilingi keliling lubang utama tersebut dan pada bagian sisi topi pelek juga terdapat lubang berbentuk elips sebagai pendingin tromol, dimana topi pelek dapat dipasang tepat pada pelek dan bagian keliling luar topi pelek tersebut dilas terhadap pelek yang dipasang topi pelek tersebut.

- Penemuan ini berhubungan dengan suatu pembungkus sedotan minuman yang dapat dibuka dengan mudah melalui penarikan kedua bagian sobekan secara berlawanan yang terdiri dari amplop sedotan yang pada bagian tepi kelilingnya berperekat panas, dan bagian sobekan. Suatu bagian sobekan tersebut dibuat di sebelah kiri dan kanan bagian memanjang pembungkus sedotan dengan kedalaman disesuaikan dengan lebar tepi berperekat panas, dan suatu bagian sobekan tersebut diberi tanda air dan sesuai dengan tempat sobekan yang telah ditentukan, dan suatu bagian sobekan tersebut dapat berbentuk garis lurus, garis miring, garis bergerigi, barisan lubang-lubang, atau bentuk-V, yang mana sobekan tersebut dapat terbuat dari satu atau dua barisan.

- Penemuan ini berhubungan dengan pembasmi gulma yang terdiri dari (A) paling tidak satu senyawa aktif pembasmi gulma dari gugus fenilsulfonilurea-fenilsulfonilurea rumus I yang tersubstitusi dan garam-garamnya yang secara pertanian diterima, yakni dapat diterima dan cocok dimana R1 adalah (C1-C8)-alkil (C3-C4)-alkenil, (C3-C4)alkinil atau (C1-C4)-alkil, yang disubstitusi mono- sampai tetra oleh radikal-radikal dari gugus yang mengandung halogen dan (C1-C2)-alkoksi; R2 adalah I atau CH2NHSO2CH3; R3 adalah metil atau metoksi; dan Z adalah N atau CH; dan (B) paling tidak satu senyawa aktif pembasmi gulma dari gugus senyawa-senyawa yang terdiri dari (B1) herbisida-herbisida yang selektif di tanaman padi, terutama terhadap rumput-rumput, (B2) herbisida-herbisida yang selektif di tanaman padi, terutama terhadap tanaman-tanaman dikotiledon yang merusak dan cyperaceae, (B3) herbisida-herbisida yang selektif di tanaman padi, terutama terhadap cyperaceae, dan (B4) herbisida-herbisida yang selektif di tanaman padi, terutama terhadap rumput-rumput dan tanaman-tanaman dikotiledon yang merusak serta terhadap tanaman-tanaman cyperaceae yang berbahaya.

- Suatu paking sambungan pipa ejos buang untuk motor bakar, yang terdiri dari; suatu rumahan paking yang berbentuk empat persegi secara melingkar, dan pada salah satu sisi kanan dari rumahan tersebut terbuka sebagai tempat memasukkan paking ke dalam rumahan tersebut, suatu gulungan paking pertama dari pelat tipis berbentuk pita, yang digulung membentuk lingkaran dan ditempatkan di bagian dalam diameter rumahan paking yang lebih kecil, suatu gulungan paking kedua dari pelat tipis berbentuk pita, yang digulung membentuk lingkaran yang memiliki diameter yang lebih besar dari gulungan pertama dan yang ditempatkan di bagian dalam diameter rumahan di sekeliling lingkaran luar dari gulungan pertama, sehingga gulungan paking kedua mengelilingi gulungan paking yang pertama. Jarak antara gulungan paking pertama dengan gulungan paking kedua berkisar 0,5 mm sampai 1 mm.

- Invensi ini berhubungan dengan suatu penyambung pipa, terutama suatu penyambung berbentuk-T (T-connector/Tee fitting) yang umum digunakan pada pipa PVC dimana di bagian dalam penyambung pipa tersebut dilengkapi dengan pisau pelubang sehingga dalam pekerjaan pemasangan penyambung tersebut tidak diperlukan lagi bor atau sejenisnya untuk melubangi pipa tersebut agar pekerjaan dapat lebih singkat, mudah dan efisien.

- Invensi ini mengenai suatu alat pengujian kombinasi yang bisa dipakai untuk pengetesan rangkak tekan beton sesuai dengan standar pengujian ASTM C yang terdiri dari sebuah dasar (16) sebagai penstabil posisi alat; dua buah batang rangka vertikal yang kokoh (17); tiga buah batang silang yang diletakkan di atas (3), tengah (8), dan bawah (4); sebuah dongkrak (13) diletakkan di antara dasar (16) dan batang silang bawah (4) yang berfungsi memberikan gaya vertikal; sebuah pegas (10) yang diletakkan di antara batang silang bawah (4) dan batang silang tengah (8) berfungsi sebagai penyangga (buffer) gaya; rangkaian 3 silinder beton yang akan diuji beserta elemen pemanasnya (5) diletakkan di antara batang silang tengah (8) dan batang silang atas (3); rangkaian silinder ini dengan elemen pemanasnya (5) dihubungkan dengan pengontrol suhu (6) agar pemanasnya memenuhi standar pengujian; dimana keseluruhan peralatan tersebut dicirikan dengan kemampuan alat melakukan dua jenis tes yaitu untuk tes pemercepat pamatangan beton dalam waktu lima jam dan tes rangkak tekan beton, yang menghasilkan suatu penghematan waktu yang cukup berarti dibandingkan dengan prosedur standar yang memerlukan waktu 28 hari.

- Suatu mesin penggiling dan pemeras bijih kelapa sawit yang terdiri dari: Beberapa pelat bergigi sebelah dalam yang disusun pada bagian keliling pelat samping, sehingga berbentuk silinder. Suatu rotor yang dipasang pada porosnya dan poros tersebut ditumpu oleh dua buah bantalan di kedua ujung poros rotor tersebut, dimana pada salah satu ujung poros rotor dipasang sebuah puli untuk dudukan sabuk-penggerak (v-belt). Suatu motor listrik yang ditempatkan di sisi luar pelat bergigi sebagai penggerak atau pemutar poros rotor, dimana salah satu ujung poros rotor. Suatu sabuk-penggerak (v-belt) yang menghubungkan putaran motor listrik dengan poros rotor. Dua buah bantalan yang ditempatkan di kedua pelat samping, yang menopang kedua ujung poros rotor, sehingga rotor dapat berputar dengan mudah pada porosnya. Dan suatu saluran pemasukan (pengumpan) biji kelapa sawit di bagian atas mesin, dan suatu saluran pengeluaran hasil pengolahan biji kelapa sawit yang ditempatkan di bagian bawah mesin.

- Suatu cincin perapat untuk pompa bahan bakar minyak (BBM) yang memiliki efisiensi teknis dan ekonomis karena memiliki sifat fisik dan mekanis yang memenuhi syarat untuk cincin perapat pompa BBM. Persyaratan tersebut adalah tahan terhadap korosi, memiliki kekerasan yang baik sesuai pemakaiannya sehingga tahan terhadap aus dan tahan lama, mudah dibentuk dan bahan bakunya mudah didapat, dimana cincin perapat untuk pompa sesuai dengan invensi ini terdiri dari komponen tetap dan komponen yang berputar serta pegas penekan cincin-cincin perapat yang berfungsi sebagai penahan kebocoran, dimana cincin-cincin perapat tersebut disukai terbuat dari bahan kuningan.

- Suatu kail pemancing ikan (9) yang tidak mudah lepas apabila sudah tertancap ke tubuh atau mulut ikan. Ujung pendek (10) dan ujung panjang (II) memiliki bentuk serupa dengan kail pancing (1) pada invensi sebelumnya. Bodi kail pada bagian lengkungan (12) memiliki alur kiri dan kanan (13) yang berbentuk pipih. Alur (13) ini dibuat sebagai penguatan lengkungan, dimana biasanya lengkungan (12) ini sering menjadi mekar atau menjadi sedikit agak lurus apabila kena gaya tarik dari ikan sebagaimana invensi terdahulu. Dengan pemberian alur penguat (13) dimaksud maka akan menambah kekuatan lengkung dari kail pemancing (9) sebagaimana invensi ini. Pada ujung panjang (11) ke arah cincin dibuat dua alur (14) terpisah sebagai penguatan bodi batang (15). Dengan demikian kail pancing menjadi lebih kuat dan dapat mencegahnya terlepas dari tancapannya ke mulut atau tubuh ikan sekalipun ikan tersebut menggelepar-gelepar.

- Invensi ini berkaitan dengan peralatan penyuling minyak atsiri yang secara sistematis mampu meningkatkan penggunaan panas, kecepatan penyulingan, efisien bahan bakar dan penggunaan air serta cara pemisahan minyak hasil penyulingan sehingga dapat memperbaiki rendemen dan mutu minyak yang dihasilkan. Alat penyuling ini memiliki kemampuan dapat mengurangi penggunaan air sampai 40% dari keadaan normal, menghemat bahan bakar sampai 25%, serta meningkatkan penggunaan panas. Pemisahan minyak hasil penyulingan dapat dilakukan baik untuk minyak dengan berat jenis lebih besar maupun lebih kecil dari air. Selain itu rendemen dan mutu minyak atsiri dapat ditingkatkan. Hal tersebut dimungkinkan karena adanya perbaikan pada: (1) mekanisme kerja proses pemanasan air pada ketel penyuling dengan cara memanfaatkan asap sisa bakar yang dilewatkan melalui pipa-pipa uap (semi-boiler), (2) sistem kohobasi dengan cara mengembalikan destilat yang sudah dipisahkan minyaknya ke dalam ketel penyuling, dan (3) alat pemisahan minyak hasil penyulingan yang cukup efisien.

- Invensi ini berhubungan dengan suatu tutup yang terdiri dari bagian atas dan flensa penutup. Bagian atas tersebut mempunyai suatu saluran keluar yang berfungsi sebagai jalan keluarnya isi botol. Saluran keluar tersebut dilengkapi dengan bagian penutup yang dihubungkan ke bagian ujung saluran keluar oleh bagian tipis dan bagian tebal. Bagian atas tersebut juga mempunyai suatu bagian anular yang mempunyai lengan sebelah dalam yang secara umum memanjang ke arah bawah dan membias ke arah luar, dan lengan sebelah luar yang secara umum memanjang ke arah luar dan membias ke arah bawah. Bagian atas tersebut juga mempunyai suatu tonjolan anular sedemikian rupa sehingga kontak dengan dan menyegel diameter luar ujung atas leher botol. Flensa penutup tersebut mempunyai suatu gigi anular yang bentuk potongan melintangnya berbentuk-V.

- Invensi ini berhubungan dengan susunan atap yang terdiri-dari suatu kerangka penyangga yang ditempatkan di atas suatu gelagar (purlin), suatu lembaran atap yang mempunyai penampang melintang yang mengikuti penampang melintang dari kerangka penyangga, dan suatu alat pengikat. Kerangka penyangga tersebut meliputi sekurang-kurangnya satu bahu penaut dan sekurang-kurangnya satu bahu pengikat yang saling terpisah satu sama lainnya dan disusun secara berselang-seling. Bahu penaut tersebut mempunyai dudukan penaut yang padanya atap saling bertautan dan bahu pengikat tersebut mempunyai dudukan pengikat yang dilengkapi dengan lubang tembus. Lembaran atap tersebut mempunyai sekurang-kurangnya satu kepala penaut dan sekurang-kurangnya satu kepala pengikat. Kepala penaut tersebut diterima pada dudukan penaut, sedangkan kepala pengikat tersebut diterima pada dudukan pengikat. Kepala pengikat tersebut mempunyai lubang tembus yang terletak tepat di atas lubang tembus dari dudukan pengikat tersebut. Invensi ini dapat juga dilengkapi dengan suatu klip pengikat yang ditempatkan di atas kepala pengikat.

- Invensi ini berhubungan dengan alat bantu pemasangan daun pintu laci yang dapat diatur dan disesuaikan dalam segala arah. Alat tersebut terdiri dari bagian pengatur dan bagian pengunci. Bagian pengatur tersebut ditekuk membentuk huruf L pada bagian tertentu. Pada bagian yang lebih panjang disebut bagian pemegang dan bagian yang lebih pendek disebut bagian pengatur. Bagian pengatur ini berfungsi untuk mengatur pemasangan daun pintu laci tersebut hingga posisi yang tepat tercapai. Sedangkan bagian pengunci mengunci bagian pengatur dengan cara mengikatnya dengan baut. Dan bagian pengunci tersebut dipasangkan pada rangka laci yang berbentuk keranjang logam dengan cara dilas.

- Bahan untuk lensa-lensa kontak yang memiliki fleksibilitas dan permeabilitas oksigen yang sangat baik dijelaskan. Bahan tersebut meliputi kopolimer yang secara mendasar terdiri dari makromer siloksana dari komponen (A) yang memiliki angka berat molekul rata-rata dari sekitar 1.000 sampai 10.000 dan dinyatakan dengan formula umum (I), monomer monoolefin tidak dapat larut dalam air dari komponen (B), dan monomer monoolefin dapat larut dalam air dari komponen (C). Lensa-lensa kontak lunak yang diperoleh dengan menyuntikkan pada cetakan dalam bentuk lensa-lensa kontak komponen (A),(B),dan (C); mengkopolimerisasi campuran monomer; dan membuat kopolimer yang dihasilkan mengandung air.

- Tujuan: Pada rangka bodi, unit pivot yang menopang lengan belakang juga berfungsi sebagai penggantung mesin dan bagian penahan standar. Berhubung kekakuan dibutuhkan untuk menahan beban yang besar itu, maka unit pivot cenderung dibuat lebih besar dan lebih berat. Oleh karena itu, tujuan penemuan ini adalah untuk menyempurnakan bagian ini guna membuat seluruh rangka bodi lebih ringkas dan lebih ringan. Pemecahan: Rangka utama (5) yang ditempatkan di atas mesin (3) dalam arah membujur rangka bodi, yang mencakup bagian utama (10) dan unit pivot (11). Ujung belakang unit pivot (11) dihubungkan ke masing-masing rangka bawah (7) yang ditempatkan miring di bawah batang sadel (6), sedangkan ujung depan dari tiap rangka bawah (7) menjulur terus ke bawah hingga membentuk perpanjangan ke bawah (12). Perpanjangan ke bawah (12) dilengkapi penopang (43) dan bagian penahan standar samping (47). Penopang (43) dapat berfungsi sebagai bagian penggantung mesin (44), bagian penahan standar utama (45), dan mampu menerima beban berat dari mesin (3), standar samping (28) dan standar utama (29) dengan memanfaatkan rangka bawah yang mempunyai kekakuan sangat tinggi (7).

- Pada alat lampu depan untuk sepeda motor atau sepeda motor roda tiga yang terdiri dari lampu sorot depan antara sepasang lampu kiri-kanan yang dipasang oleh tutup kemudi yang menutupi batang kemudi, untuk memungkinkan sumbu optik lampu sorot depan ini diatur dengan mudah satu demi satu berdasarkan lampu sorot depan. Poros topang (53) yang dimiliki oleh lampu sorot depan (41) di kedua sisi ditopang secara dapat berputar oleh sepasang lampu kiri-kanan (42).

- Diungkapkan suatu proses untuk pemulihan distilasi dari monoetilena glikol pemurnian tinggi dari produk hidrolisis etilena oksida dengan pengeringan tekanan, pengeringan pakum dan distilasi pemurnian berikutnya, yang terdiri dari kolum-kolum pengeringan tekanan atau sedikitnya kolum pengeringan tekanan pertama dari baterai (2, 3, 4) yang memiliki bagian pemisahan dengan sedikitnya satu tahap pemisahan, lebih disukai dengan dari 2 sampai 10 tahap pemisahan, terutama lebih disukai dengan dari 3 sampai 6 tahap, dan bagian dati aliran atas kolum-(kolum) pengeringan tekanan (2, 3, 4) yang memiliki bagian pemisahan yang dihilangkan dari sistem.

- Penemuan terkait dengan massa mirip-pasta yang dapat digunakan dalam elemen elektrokimia yang terdiri dari matriks yang paling sedikit mengandung atau terdiri dari satu polimer organik, prekursornya, atau prepolimernya, dan bahan anorganik yang dapat diaktifkan secara elektrokimia yang tidak dapat larut dalam matriks dan yang berbentuk substansi padat, dimana (a) massa yang paling sedikit terdiri dari 60% vol. (B) dan, jika (B) berupa bahan elektroda, (B) dikerjakan menjadi matriks (A) tanpa bantuan pelarut atau bahan pengembung untuk polimer organik tersebut, prekursornya, atau prepolimernya dan/atau (b) massa yang paling sedikit terdiri dari kurang lebih 60% vol. (B) dan, jika (B) berupa bahan elektroda, dapat dihasilkan dimana (B) dikerjakan menjadi matriks (A) yang juga mengandung pemlastis untuk polimer organik, dan pemlastis selanjutnya ditiadakan dengan menggunakan pelarut yang sesuai, (C) dan/atau (C) campuran juga mengandung elektron ion padat dan/atau penghantar ampuran yang berbeda dari (B) dan yang paling sedikit ada di batas butir antara (A) dan (B) sebagai lapis tipis. Penemuan lebih jauh terkait dengan lapis-lapis yang dapat berdiri sendiri atau yang ditempatkan pada substrat di samping lapis-lapis komposit yang dibuat dari lapis-lapis tersebut dan yang memiliki properti elektrokimia, misalnya sel-sel elektrokimia yang dapat diisi kembali. Penemuan juga menjelaskan metoda menghasilkan massa, lapis, dan lapis komposit.

- Komposisi farmasi yang stabil dalam bentuk liofil mengandung: senyawa siklik polipeptida diwakili oleh formula umum (I): dimana R1 adalah atom hidrogen atau gugus asil serta R2 dan R3 adalah atom hidrogen atau gugus hidroksil yang sama atau berbeda, atau garamnya dan penstabil.

- Sebuah kunci yang dilengkapi dengan suatu penggerak. Kunci tersebut juga memiliki suatu sarana operasi dan sarana interaksi. Sewaktu kunci tersebut dimasukkan ke dalam sebuah gembok, suatu gaya dipasangkan ke sarana operasi dan posisi dari sarana interaksi berubah. Penggerakan sarana interaksi digunakan dalam mekanisme penggembokan dan/atau bukan-penggembokan dari gembok tersebut. Sebuah gagang kunci dan gembok tersebut juga tersedia yang bergabung dalam semacam suatu mekanisme.

- Uraian di atas adalah metode untuk memancarkan sinyal kanal dalam stasiun basis dari sistem komunikasi bergerak yang mengacak sinyal kanal umum menggunakan kode pengacak primer untuk mengidentifikasi stasiun basis. Metode tersebut terdiri dari menentukan pengidentifikasi (ID) dari kode pengacak sekunder, setelah penerimaan permintaan penetapan kanal tertuju dari stasiun bergerak; memancarkan ID kode pengacak sekunder yang telah ditentukan ke stasiun bergerak dan menunggu respon; setelah penerimaan pesan respon dari stasiun bergerak, menghasilkan kode pengacak primer dan kode pengacak sekunder menggunakan ID kode pengacak primer dan ID kode pengacak sekunder tersebut; dan mengacak sinyal kanal umum menggunakan kode pengacak primer, mengacak sinyal kanal tertuju menggunakan kode pengacak sekunder, dan memancarkan sinyal-sinyal kanal yang telah diacak.

- Sebuah kunci yang dilengkapi dengan suatu penggerak. Kunci tersebut juga memiliki suatu sarana operasi dan sarana interaksi. Sewaktu kunci tersebut dimasukkan ke dalam sebuah gembok, suatu gaya dipasangkan ke sarana operasi dan posisi dari sarana interaksi berubah. Penggerakan sarana interaksi digunakan dalam mekanisme penggembokan dan/atau bukan-penggembokan dari gembok tersebut. Sebuah gagang kunci dan gembok tersebut juga tersedia yang bergabung dalam semacam suatu mekanisme.

- Penemuan ini diarahkan pada komposisi-komposisi farmasi padat berbentuk dosis oral untuk pelepasan terus menerus yang mengandung jumlah terapi zat aktif farmasi, hidroksipropil metil selulosa dan polimer hidrofilik non-ionik yang dipilih dari kelompok yang terdiri dari hidroksietil selulosa yang memiliki berat molekul rata-rata 90.000 sampai 1.300.000, hidroksipropil selulosa yang memiliki berat molekul rata-rata dari 370.000 sampai 1.500.000, dan poli(etilena oksida) yang memiliki berat molekul rata-rata dari 100.000 sampai 500.000.

- Suatu profiler kerapatan untuk mengukur suatu profil kerapatan dari suatu media yang meliputi sedikitnya dua fase berair dan fase gas meliputi suatu deret sumber yang terdistribusi secara aksial yang menyediakan sedikitnya 10 gelombang radiasi pengion terkolimasi suatu deret detektor radiasi yang terdistribusi secara aksial, masing-masing detektor dihubungkan penggunaanya dengan salah satu dari gelombang tersebut dan menghasilkan suatu gelombang output sehubungan dengan radiasi kejadian; dan suatu penganalisa untuk sinyal output detektor untuk menentukan kerapatan media yang dilintasi oleh gelombang-gelombang radiasi tersebut.

- Metode dan peralatan - untuk menentukan posisi di dalam pipa - menghasilkan penentuan tepat lokasi dan karakteristik bersangkutan pada masing-masing sambungan pipa sebuah sumur, saluran pipa lintas-wilayah atau saluran pengiriman fluida lainnya. Sistem tersebut mencakup alat identifikasi radio aktif dan pasif pada setiap sambungan di rangkaian pipa atau selubung. Alat tersebut sebaiknya tersekat rapat di dalam penyekat elastis yang ditempatkan di antara masing-masing pipa atau sambungan selubung. Perkakas saluran pipa mencakup transmiter dan penerima radio, dengan transmiter mengadakan transmisi pada frekuensi tang dipilih untuk menimbulkan resonansi alat identifikasi. Respons resonansi masing-masing alat dideteksi oleh penerima dalam perkakas saluran pipa, dengan respons dikirimkan ke permukaan melalui kabel konduktor yang terhubung ke perkakas. Alternatif lain, perkakas dapat mencakup alat penyimpan informasi sampai perkakas dapat diambil kembali dari sumur atau pipa. Sistem penyimpanan dan pengambilan kembali informasi mencakup informasi tentang lokasi masing-masing alat identifikasi di dalam sumur atau pipa, misalnya panjang atau kedalaman, diameter pipa atau selubung, karakteristik geologis yang terekam sebelumnya dan strata di masing-masing lokasi alat identifikasi, dan sebagainya. Sistem dapat menghitung setiap alat pada saat perkakas melewati pipa guna menentukan lokasi perkakas di setiap titik. Alternatif lain, masing-masing alat identifikasi dapat memberikan sinyal yang berbeda, dengan perkakas mentransmisi sinyal ke permukaan (atau menyimpan sinyal untuk diambil kembali kemudian) tempat sistem menghubungkan sinyal tersebut dengan informasi yang terekam sebelumnya untuk lokasi tertentu itu.

- Dalam suatu penerima OFDM, suatu pulsa sinkronisasi untuk menentukan suatu jendela Transformasi Fourier Cepat (Fast Fourier Transformation) dibangkitkan dengan menguji keluaran korelator untuk menemukan sub-interval dalam yang mana ada korelasi maksimum antara simbol yang dipisahkan oleh panjang bagian yang berguna dari simbol itu. Pulsa sinkronisasi itu dibangkitkan selama sub-interval (102) ini. Pengaturan ke waktu pulsa sinkronisasi dibuat hanya jika error sekarang signifikan dan menetap. Suatu sinyal yang menyatakan jumlah pengaturan yang digunakan untuk menentukan rotasi fase diterapkan ke keluaran rangkaian FFT itu.

- Suatu metode pemekaran suatu tabung baja yang dapat dimekarkan terdiri dari tahap: pemipihan tabung yang tak dimekarkan; pengangkutan tabung baja pipih yang belum dibulatkan tersebut ke suatu lokasi pada atau di dekat lokasi dimana tabung tersebut akan dipasang; pembulatan tabung tersebut sebelum penempatan posisi tabung tersebut pada lokasinya; dan pembentangan tabung tersebut setidaknya sepanjang bagian panjangnya sebelum atau setelah tabung tersebut ditempatkan pada lokasinya.

- Suatu senyawa menurut formula (I) di mana zo adalah suatu cincin fenil, suatu senyawa heteroaromatis C4 sampai C9 yang mengandung satu atau lebih heteroatom, atau gugus naftalenil, 5,6,7,8-tetrahidronaftalenil atau bifenil; yang menunjukkan afinitas tinggi untuk reseptor M3 muskarinat (Hm3).

3. Petunjuk Penggunaan:

Input Pengguna: Pengguna akan menginputkan sebuah abstrak yang perlu diperbaiki.

Proses Perbaikan:

Analisis Struktur: Pelajari struktur kalimat, penggunaan terminologi teknis, dan format penulisan berdasarkan contoh abstrak yang telah diberikan.
Perbaikan Bahasa: Perbaiki tata bahasa, ejaan, dan keterbacaan abstrak tanpa mengubah makna asli.
Konsistensi Terminologi: Pastikan penggunaan istilah teknis konsisten dan sesuai dengan konteks.
Penyusunan Ulang: Jika diperlukan, susun ulang kalimat atau paragraf untuk meningkatkan alur logis dan kejelasan informasi.
Penghilangan Redundansi: Hilangkan informasi yang berulang atau tidak relevan untuk menjaga keefisienan abstrak.
Output: Berikan abstrak yang telah diperbaiki dalam format yang rapi dan terstruktur.

4. Pedoman Tambahan:

Kepatuhan Bahasa: Pastikan semua perbaikan dilakukan dalam bahasa Indonesia yang baik dan benar.

Keakuratan Teknis: Jangan mengubah informasi teknis atau data penting dalam abstrak. Fokuslah pada peningkatan kualitas penulisan.

Keamanan Data: Pastikan bahwa abstrak yang diproses tidak mengandung informasi pribadi atau sensitif yang tidak perlu.
"""

def improve_abstract(user_input):
    payload = {
        "messages": [
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_input
            }
        ],
        "temperature": 0.7,
        "top_p": 0.95,
        "max_tokens": 800
    }

    try:
        response = requests.post(ENDPOINT, headers=headers, json=payload)
        response.raise_for_status()
        result = response.json()
        assistant_reply = result['choices'][0]['message']['content']
        return assistant_reply
    except requests.RequestException as e:
        return f"Gagal mendapatkan respons dari API. Error: {e}"

# Inisialisasi session state untuk menyimpan riwayat pesan
if 'generated' not in st.session_state:
    st.session_state['generated'] = []
if 'past' not in st.session_state:
    st.session_state['past'] = []

# Membuat tampilan Streamlit dengan layout wide
st.set_page_config(page_title="📝 Chatbot Perbaikan Abstrak", layout="wide")

# Judul aplikasi
st.title("📝 Chatbot Perbaikan Abstrak")

# Membuat container untuk chat
response_container = st.container()
input_container = st.container()

with input_container:
    # Input abstrak dari pengguna di bagian bawah
    user_input = st.text_area("Masukkan Abstrak Anda:", height=100, key="input")
    submit_button = st.button("📤 Kirim")

if submit_button and user_input:
    if user_input.strip() == "":
        st.warning("Silakan masukkan abstrak yang ingin diperbaiki.")
    else:
        with st.spinner("🔄 Memproses..."):
            assistant_reply = improve_abstract(user_input)
        # Simpan pesan ke session state
        st.session_state.past.append(user_input)
        st.session_state.generated.append(assistant_reply)

with response_container:
    if st.session_state['generated']:
        for i in range(len(st.session_state['generated'])):
            message(st.session_state["past"][i], is_user=True, key=str(i) + '_user')
            message(st.session_state["generated"][i], key=str(i))
    else:
        st.info("Silakan masukkan abstrak Anda di bawah dan tekan 'Kirim' untuk memulai.")

# Catatan tambahan
st.markdown("---")
st.markdown("**Catatan:** Chatbot ini hanya berfungsi untuk memperbaiki abstrak. Pertanyaan di luar konteks perbaikan abstrak tidak akan dijawab.")